### ISSUE TITLE
Need docker version

### ISSUE THREAD

**Issue by cyw3** [exaloop/codon#102]
Hi, I want to use codon in a docker. Can you provide a docker image version?

Thanks!

**Comment by Sparkenstein** [comment]
shouldn't it be just running the install script

```
/bin/bash -c "$(curl -fsSL https://exaloop.io/install.sh)"
```
inside the docker? after than codon should be available inside docker.  you should be able to run this in any linux docker container. Not sure if there's a specific need of official docker distribution but I will leave that to authors

**Comment by cyw3** [comment]
Got it.

**Comment by arshajii** [comment]
FYI this is available now: https://hub.docker.com/r/exaloop/codon
