### ISSUE TITLE
slow dict().setdefault when default value is a function call.

### ISSUE THREAD

**Issue by ghuls** [exaloop/codon#106]
`dict().setdefault("key", function_to_set_default_value(value))` is much slower than first checking if the key exists and only then calling the function. Even the case where the function shouldn't be called with .set_default() (as the key already exists), it is slow.

```python
❯ cat slow_dict_set_default.codon 
import sys

d = {
  "a": 3,
  "b": 5,
  "c": 7,
}

def conv(y):
    return int(str(int(str(int(str(y))))))

x = 0
i = 0

for i in range(100000000):
    x = d.setdefault(sys.argv[1], conv(9))

print(x, i)
```

```python
❯ cat fast_dict_check_key_exist.codon 
import sys

d = {
  "a": 3,
  "b": 5,
  "c": 7,
}

def conv(y):
    return int(str(int(str(int(str(y))))))

x = 0
i = 0

for i in range(100000000):
    if sys.argv[1] not in d:
        x = conv(9)
        d[sys.argv[1]] = x
    else:
        x = d[sys.argv[1]]

print(x, i)
```

```bash
❯ time codon run --release slow_dict_set_default.codon "a"
3 99999999

real	0m24,234s
user	0m26,798s
sys	0m0,754s

❯ time codon run --release slow_dict_set_default.codon "d"
9 99999999

real	0m24,125s
user	0m26,355s
sys	0m0,892s


❯ time codon run --release fast_dict_check_key_exist.codon "a"
3 99999999

real	0m1,968s
user	0m1,936s
sys	0m0,034s

❯ time codon run --release fast_dict_check_key_exist.codon "d"
9 99999999

real	0m1,970s
user	0m1,943s
sys	0m0,028s
```

**Comment by arshajii** [comment]
Hi Gert -- the argument to `setdefault` will be evaluated regardless of what happens afterwards, just like in Python. E.g. see https://stackoverflow.com/questions/17532929/how-to-implement-a-lazy-setdefault. In general for any `f(g())` the call to `g` is done before `f` is invoked at all.

**Comment by ghuls** [comment]
Thanks for the explanation. Seems like I only used dict().setdefault() with plain default values before instead of a heavy function.
