### ISSUE TITLE
codon_jit.cpython-310-x86_64-linux-gnu.so: undefined symbol:

### ISSUE THREAD

**Issue by lionnung** [exaloop/codon#107]
lion@lion-VirtualBox:~/source/codon$ echo $CODON_DIR
/home/lion/Downloads/codon-deploy/
lion@lion-VirtualBox:~/source/codon$ 
lion@lion-VirtualBox:~/source/codon$ python3 ./fib.py
Traceback (most recent call last):
  File "/home/lion/source/codon/./fib.py", line 28, in <module>
    import codon
  File "/home/lion/.local/lib/python3.10/site-packages/codon/__init__.py", line 5, in <module>
    from .decorator import jit, convert, JITError
  File "/home/lion/.local/lib/python3.10/site-packages/codon/decorator.py", line 17, in <module>
    from .codon_jit import JITWrapper, JITError, codon_library
ImportError: /home/lion/.local/lib/python3.10/site-packages/codon/codon_jit.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN5codon3jit14jitExecuteSafeEPNS0_3JITERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_ib
lion@lion-VirtualBox:~/source/codon$ 
lion@lion-VirtualBox:~/source/codon$ ~/Downloads/codon-deploy/bin/codon run -release ./fib.py 
fib.py:28:8-13: error: no module named 'codon'
fib.py:39:2-11: error: no module named 'codon'
fib.py:54:47-61: error: name 'is_prime_codon' is not defined

**Comment by Au-ChiKin** [comment]
> 

@lionnung Could you please how did you solve the undefined symbol?

**Comment by cqlp1314** [comment]
how to solve undefined symbol error ? man

**Comment by inumanag** [comment]
Working on it. Which OS / environment are you using, please?

**Comment by arshajii** [comment]
This should work with the latest Codon release (0.15.3) and latest `codon-jit` (0.1.1). Please let me know if there are still issues and we can reopen.
