### ISSUE TITLE
C/C++ integration ERROR: relocation R_X86_64_32 against `.bss' can not be used when making a shared object

### ISSUE THREAD

**Issue by guolanting** [exaloop/codon#108]
I am following the document: https://docs.exaloop.io/codon/interoperability/cpp.
when generating `libfoo.so` the error occurs as belows.
![image](https://user-images.githubusercontent.com/62043931/207495369-4531e20c-5eb4-4538-9911-e90f446ef9b1.png)

```
$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE
```

**Comment by ghuls** [comment]
This allows it to be build:
```bash
codon build --relocation-model=pic -o libfoo.so foo.codon
```

**Comment by guolanting** [comment]
![image](https://user-images.githubusercontent.com/62043931/207586157-5b9e2d74-a4d6-4ead-9b39-2b938d1e2184.png)

using `gcc foo.c libfoo.so /home/XXX/.codon/lib/codon/libcodonrt.so -o foo` ,  the error changes to `libcodonrt.so: undefined reference to `__kmpc_set_gc_callbacks@VERSION`

**Comment by guolanting** [comment]
finaly, I solved this problem by adding ${HOME}/.codon/lib/codon to LD_LIBRARY_PATH and `gcc foo.c -o foo -L. -lfoo`

**Comment by ghuls** [comment]
```bash
❯ codon build --relocation-model=pic -o libfoo.so foo.codon

# Library flag should be after the c files.
❯ gcc -o foo -L. -l foo foo.c
/usr/bin/ld: /tmp/ccYCRoY3.o: in function `main':
foo.c:(.text+0xe): undefined reference to `foo'
collect2: error: ld returned 1 exit status

# This works
❯ gcc -o foo -L. foo.c -lfoo

❯ LD_LIBRARY_PATH=${HOME}/software/exaloop/codon/codon-0.15.1/lib/codon:. ./foo 
0
1
4
9
16
25
36
49
64
81
100
```

**Comment by ghuls** [comment]
@inumanag 
Can you update: https://docs.exaloop.io/codon/interoperability/cpp,
 with the correct codon build and gcc commands?

The C snippet is using the wrong format string. it should be `%li`.
```
❯ cat foo.c
#include <stdint.h>
#include <stdio.h>

int64_t foo(int64_t);

int main() {
    printf("%li\n", foo(10));
}
```
