### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by cyw3** [exaloop/codon#111]
test.py
```python
import argparse

class Test(object):
    def __init__(self):
        print("Test---------\n")
        self.argparser = argparse.ArgumentParser()

```

test.codon
```codon

from python import test

if __name__ == "__main__":
    test.Test()
```

I have the demo above, and run it with codon, and i get the error `PyError: list index out of range`

```bash
$ codon run test.codon
Test---------

PyError: list index out of range

Raised from: pyobj.exc_check:0
/data/test/codon-deploy/lib/codon/stdlib/internal/python.codon:623:13

Backtrace:
  [0x7fc1ad3e4af3] GCC_except_table171 at /data/test/codon-deploy/lib/codon/stdlib/internal/python.codon:623:13
  [0x7fc1ad3e4b20] GCC_except_table171 at /data/test/codon-deploy/lib/codon/stdlib/internal/python.codon:626:9
  [0x7fc1ad3e5688] GCC_except_table171 at /data/test/codon-deploy/lib/codon/stdlib/internal/python.codon:650:68
  [0x7fc1ad3e6915] GCC_except_table171 at /workspace/codon.py:14:5
Aborted (core dumped)
```

**Comment by arshajii** [comment]
Hi @cyw3 -- here's an example of how this can be done (I just took the simple example from the `argparse` docs):

```python
# .codon file
import sys
from python import argparse

parser = argparse.ArgumentParser(
                    prog = 'ProgramName',
                    description = 'What the program does',
                    epilog = 'Text at the bottom of help')

parser.add_argument('filename')           # positional argument
parser.add_argument('-c', '--count')      # option that takes a value
parser.add_argument('-v', '--verbose',
                    action='store_true')  # on/off flag

args = parser.parse_args(sys.argv[1:])
print(args.filename, args.count, args.verbose)
```

Just remember to set the `CODON_PYTHON` env variable to the Python library as described [here](https://docs.exaloop.io/codon/interoperability/python).

**Comment by cyw3** [comment]
> Hi @cyw3 -- here's an example of how this can be done (I just took the simple example from the `argparse` docs):
> 
> ```python
> # .codon file
> import sys
> from python import argparse
> 
> parser = argparse.ArgumentParser(
>                     prog = 'ProgramName',
>                     description = 'What the program does',
>                     epilog = 'Text at the bottom of help')
> 
> parser.add_argument('filename')           # positional argument
> parser.add_argument('-c', '--count')      # option that takes a value
> parser.add_argument('-v', '--verbose',
>                     action='store_true')  # on/off flag
> 
> args = parser.parse_args(sys.argv[1:])
> print(args.filename, args.count, args.verbose)
> ```
> 
> Just remember to set the `CODON_PYTHON` env variable to the Python library as described [here](https://docs.exaloop.io/codon/interoperability/python).

When I run the demo you provided, I get the error `PyError: 0`:
```bash
$ codon run  test.codon
usage: ProgramName [-h] [-c COUNT] [-v] filename

What the program does

positional arguments:
  filename

optional arguments:
  -h, --help            show this help message and exit
  -c COUNT, --count COUNT
  -v, --verbose

Text at the bottom of help
PyError: 0

Raised from: pyobj.exc_check:0
/data/test/codon-deploy/lib/codon/stdlib/internal/python.codon:623:13

Backtrace:
  [0x7f0dff8c3f03] GCC_except_table255 at /data/test/codon-deploy/lib/codon/stdlib/internal/python.codon:623:13
  [0x7f0dff8c3f30] GCC_except_table255 at /data/test/codon-deploy/lib/codon/stdlib/internal/python.codon:626:9
  [0x7f0dff8c6192] GCC_except_table255 at /data/test/codon-deploy/lib/codon/stdlib/internal/python.codon:650:68
  [0x7f0dff8c782c] GCC_except_table255 at /workspace/test.codon:30:8
Aborted (core dumped)
```

**Comment by ghuls** [comment]
It happens because filename is not specified.

This works:
```python
codon run argparse_python.codon -c 5 -v blabla.txt
['-c', '5', '-v', 'blabla.txt']
```

**Comment by arshajii** [comment]
Closing this for now but please let me know if you have any other questions about this.
