### ISSUE TITLE
Can't import codon as a decorator

### ISSUE THREAD

**Issue by Joeywzr** [exaloop/codon#113]
Python 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> import codon
[1]    5779 segmentation fault (core dumped)  python3

astunparse-1.6.3 
cython-0.29.32 
wheel-0.37.1

**Comment by arshajii** [comment]
This should work with the latest Codon release (0.15.3) and latest `codon-jit` (0.1.1). Please let me know if there are still issues and we can reopen.

**Comment by Joeywzr** [comment]
Thanks for helping! I've upgraded it and I met a new problem which is same as #107.

> Python 3.6.9 (default, Sep 25 2019, 14:17:00) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> import codon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amos/gentoo/usr/lib64/python3.6/site-packages/codon_jit-0.1.1-py3.6-linux-x86_64.egg/codon/__init__.py", line 5, in <module>
    from .decorator import jit, convert, JITError
  File "/home/amos/gentoo/usr/lib64/python3.6/site-packages/codon_jit-0.1.1-py3.6-linux-x86_64.egg/codon/decorator.py", line 17, in <module>
    from .codon_jit import JITWrapper, JITError, codon_library
ImportError: /home/amos/gentoo/usr/lib64/python3.6/site-packages/codon_jit-0.1.1-py3.6-linux-x86_64.egg/codon/codon_jit.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN5codon3jit7jitInitERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE


> ~ $ ldd -r /home/amos/gentoo/usr/lib64/python3.6/site-packages/codon_jit-0.1.1-py3.6-linux-x86_64.egg/codon/codon_jit.cpython-36m-x86_64-linux-gnu.so
        linux-vdso.so.1 (0x00007ffd855ef000)
        libcodonrt.so => /home/wangzengrui/.codon/lib/codon/libcodonrt.so (0x00007fc49ad5c000)
        libpython3.6m.so.1.0 => /home/amos/gentoo/usr/lib64/libpython3.6m.so.1.0 (0x00007fc49aa4d000)
        libcodonc.so => /home/wangzengrui/.codon/lib/codon/libcodonc.so (0x00007fc49365f000)
        libstdc++.so.6 => /home/amos/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/libstdc++.so.6 (0x00007fc4933ea000)
        libm.so.6 => /home/amos/gentoo/lib64/libm.so.6 (0x00007fc49329f000)
        libgcc_s.so.1 => /home/amos/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/libgcc_s.so.1 (0x00007fc493285000)
        libpthread.so.0 => /home/amos/gentoo/lib64/libpthread.so.0 (0x00007fc493260000)
        libc.so.6 => /home/amos/gentoo/lib64/libc.so.6 (0x00007fc49308f000)
        libomp.so => /home/wangzengrui/.codon/lib/codon/libomp.so (0x00007fc492fa5000)
        librt.so.1 => /home/amos/gentoo/lib64/librt.so.1 (0x00007fc492f9b000)
        libdl.so.2 => /home/amos/gentoo/lib64/libdl.so.2 (0x00007fc492f95000)
        /home/amos/gentoo/lib64/ld-linux-x86-64.so.2 (0x00007fc49b25b000)
        libutil.so.1 => /home/amos/gentoo/lib64/libutil.so.1 (0x00007fc492f90000)
undefined symbol: _ZN5codon3jit7jitInitERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE  (/home/amos/gentoo/usr/lib64/python3.6/site-packages/codon_jit-0.1.1-py3.6-linux-x86_64.egg/codon/codon_jit.cpython-36m-x86_64-linux-gnu.so)
undefined symbol: _ZN5codon3jit13getJITLibraryB5cxx11Ev (/home/amos/gentoo/usr/lib64/python3.6/site-packages/codon_jit-0.1.1-py3.6-linux-x86_64.egg/codon/codon_jit.cpython-36m-x86_64-linux-gnu.so)
undefined symbol: _ZN5codon3jit16jitExecutePythonEPNS0_3JITERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorIS8_SaIS8_EESA_SF_Pvb    (/home/amos/gentoo/usr/lib64/python3.6/site-packages/codon_jit-0.1.1-py3.6-linux-x86_64.egg/codon/codon_jit.cpython-36m-x86_64-linux-gnu.so)
undefined symbol: _ZN5codon3jit14jitExecuteSafeEPNS0_3JITERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_ib   (/home/amos/gentoo/usr/lib64/python3.6/site-packages/codon_jit-0.1.1-py3.6-linux-x86_64.egg/codon/codon_jit.cpython-36m-x86_64-linux-gnu.so)
