### ISSUE TITLE
CommandLine Error: Option 'use-dbg-addr' registered more than once

### ISSUE THREAD

**Issue by DanInSpace104** [exaloop/codon#124]
i installed codon with install.sh script, to use it in my existing project as @codon.jit 
codon==0.15.3
codon-jit==0.1.1 

but when i launch my program i get 
```
: CommandLine Error: Option 'use-dbg-addr' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
[1]    39236 IOT instruction (core dumped)  python3 main.py
```

**Comment by arshajii** [comment]
Hi @DanInSpace104 -- first time I'm seeing this error! What OS and architecture are you on? Not sure what's in `main.py`, but I'm assuming you get the same error on a simple test program?

**Comment by DanInSpace104** [comment]
@arshajii i created test file, codon.jit decorator works fine.
I am trying to use it inside PyQt5 project, but i am wrapping 'clean' function that deals with variables of built-in types

**Comment by inumanag** [comment]
@DanInSpace104 Can you please tell me more about your environment (OS, version, etc.)? I'd like to reproduce it if possible.
