### ISSUE TITLE
CMake Generate step failed. 

### ISSUE THREAD

**Issue by Firefly-Dance** [exaloop/codon#129]
I use arm64 Linux device, so i download code and try to build from source, after typing 
> cmake -S . -B build -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_DIR=$(llvm-config --cmakedir) \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++

and i got

>CMake Error at build/_deps/xz-src/CMakeLists.txt:521 (add_executable):
  The install of the xzdec target requires changing an RPATH from the build
  tree, but this is not supported with the Ninja generator unless on an
  ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set
  to avoid this relinking step.

>CMake Error at build/_deps/xz-src/CMakeLists.txt:559 (add_executable):
  The install of the xz target requires changing an RPATH from the build
  tree, but this is not supported with the Ninja generator unless on an
  ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set
  to avoid this relinking step.

>CMake Error at build/_deps/openmp-src/runtime/src/CMakeLists.txt:149 (add_library):
  The install of the omp target requires changing an RPATH from the build
  tree, but this is not supported with the Ninja generator unless on an
  ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set
  to avoid this relinking step.

>CMake Error at build/_deps/openmp-src/runtime/src/CMakeLists.txt:149 (add_library):
  The install of the omp target requires changing an RPATH from the build
  tree, but this is not supported with the Ninja generator unless on an
  ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set
  to avoid this relinking step.

So, what should I do next?

**Comment by ijustlovemath** [comment]
It says the Ninja generator doesn't support the RPATH setup. Use the default generator by not specifying `-G <generator>`.

**Comment by Firefly-Dance** [comment]
I solve the problem by adding
> -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON

at the end.
Thanks for your help.

**Comment by etoilestar** [comment]
> I solve the problem by adding
> 
> > -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON
> 
> at the end. Thanks for your help.

it doesn't work for me.
