### ISSUE TITLE
C++ namespace support for Codon import statement

### ISSUE THREAD

**Issue by ct-clmsn** [exaloop/codon#132]
Attempts to import C++ functions, nested in C++ namespaces, using Codon have been unsuccessful. Wasn't able to find examples or documentation for a solution.

Example of the situation...

C++ code
```
namespace example {

    void hello() { ... }

}
```
Codon import of `example::hello` using the "C" module
```
from C import example.hello()
```

Would like to be able to handle deeper C++ namespace nesting. Hoping the example makes for a good starting point. Maybe a CPP or CXX namespace is required to handle name mangling? Thanks in advance for the time and attention!

**Comment by arshajii** [comment]
Hi @ct-clmsn -- currently Codon needs to use C ABI functions (i.e. `extern "C"`), so the recommended approach for C++ is to wrap the functions you want to call within Codon in an `extern "C"` function.

We *are* planning to support direct C++ as well, although it isn't trivial as you need to integrate a C++ frontend like Clang.
