### ISSUE TITLE
Cmake build faild

### ISSUE THREAD

**Issue by DongYangYang621** [exaloop/codon#133]
cmake --build build --config Release

FAILED: CMakeFiles/codonc.dir/codon/parser/visitors/simplify/ctx.cpp.o
/usr/bin/clang++  -Dcodonc_EXPORTS -I../. -I_deps/peglib-src -I_deps/toml-src/include -I_deps/semver-src/include -I_deps/fmt-src/include -pedantic -fvisibility-inlines-hidden -Wno-return-type-c-linkage -Wno-gnu-zero-variadic-macro-arguments -Wno-deprecated-declarations -O3 -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=gnu++17 -MD -MT CMakeFiles/codonc.dir/codon/parser/visitors/simplify/ctx.cpp.o -MF CMakeFiles/codonc.dir/codon/parser/visitors/simplify/ctx.cpp.o.d -o CMakeFiles/codonc.dir/codon/parser/visitors/simplify/ctx.cpp.o -c ../codon/parser/visitors/simplify/ctx.cpp
In file included from ../codon/parser/visitors/simplify/ctx.cpp:3:
In file included from .././codon/parser/visitors/simplify/ctx.h:14:
In file included from .././codon/parser/cache.h:11:
In file included from .././codon/parser/ast.h:6:
In file included from .././codon/parser/ast/expr.h:11:
In file included from .././codon/parser/ast/types.h:5:
In file included from .././codon/parser/ast/types/class.h:10:
In file included from .././codon/parser/ast/types/type.h:11:
In file included from .././codon/parser/common.h:17:
In file included from .././codon/util/common.h:14:
.././codon/compiler/error.h:496:74: error: missing default argument on parameter 'args'
void E(Error e, const codon::SrcInfo &o = codon::SrcInfo(), const TA &...args) {
                                                                         ^
../codon/parser/visitors/simplify/ctx.cpp:33:5: note: in instantiation of function template specialization 'codon::error::E<std::__cxx11::basic_string<char> >' requested here
    E(Error::ID_INVALID_BIND, getSrcInfo(), name);
    ^
1 error generated.

**Comment by DongYangYang621** [comment]
i execute "cmake --build build --config Release" got the above error, what should i do?

**Comment by inumanag** [comment]
@DongYangYang621 

Can you please provide more information (OS? Architecture? Compiler?).

**Comment by timIdeaTech** [comment]
I am running into the same issue. I have followed and fixed (RPATH issue) the steps on the compiling page and have reached the final build cmake as per below. I am on an Ubuntu 20.04 arm64 platform (see uname -a and cat /etc/os-release at the bottom). I could live with an Ubuntu 20.04 arm64 binary too :^)

tim@sniirm-z001:~/proj/codon$ cmake --build build --config Release
[2/116] Building CXX object CMakeFiles/codonc.dir/codon/parser/ast/stmt.cpp.o
FAILED: CMakeFiles/codonc.dir/codon/parser/ast/stmt.cpp.o
/usr/bin/clang++  -Dcodonc_EXPORTS -I../. -I_deps/peglib-src -I_deps/toml-src/include -I_deps/semver-src/include -I_deps/fmt-src/include -pedantic -fvisibility-inlines-hidden -Wno-return-type-c-linkage -Wno-gnu-zero-variadic-macro-arguments -Wno-deprecated-declarations -O3 -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=gnu++17 -MD -MT CMakeFiles/codonc.dir/codon/parser/ast/stmt.cpp.o -MF CMakeFiles/codonc.dir/codon/parser/ast/stmt.cpp.o.d -o CMakeFiles/codonc.dir/codon/parser/ast/stmt.cpp.o -c ../codon/parser/ast/stmt.cpp
In file included from ../codon/parser/ast/stmt.cpp:3:
In file included from .././codon/parser/ast/stmt.h:10:
In file included from .././codon/parser/ast/expr.h:11:
In file included from .././codon/parser/ast/types.h:5:
In file included from .././codon/parser/ast/types/class.h:10:
In file included from .././codon/parser/ast/types/type.h:11:
In file included from .././codon/parser/common.h:17:
In file included from .././codon/util/common.h:13:
.././codon/compiler/error.h:496:74: error: missing default argument on parameter 'args'
void E(Error e, const codon::SrcInfo &o = codon::SrcInfo(), const TA &...args) {
                                                                         ^
.././codon/util/common.h:145:3: note: in instantiation of function template specialization 'codon::error::E<std::__cxx11::basic_string<char> >' requested here
  E(e, o.getSrcInfo(), args...);
  ^
../codon/parser/ast/stmt.cpp:389:7: note: in instantiation of function template specialization 'codon::E<std::__cxx11::basic_string<char> >' requested here
      E(Error::FN_ARG_TWICE, a, n);
      ^
In file included from ../codon/parser/ast/stmt.cpp:3:
In file included from .././codon/parser/ast/stmt.h:10:
In file included from .././codon/parser/ast/expr.h:11:
In file included from .././codon/parser/ast/types.h:5:
In file included from .././codon/parser/ast/types/class.h:10:
In file included from .././codon/parser/ast/types/type.h:11:
In file included from .././codon/parser/common.h:17:
In file included from .././codon/util/common.h:13:
.././codon/compiler/error.h:496:74: error: missing default argument on parameter 'args'
void E(Error e, const codon::SrcInfo &o = codon::SrcInfo(), const TA &...args) {
                                                                         ^
.././codon/util/common.h:141:3: note: in instantiation of function template specialization 'codon::error::E<char [10], std::__cxx11::basic_string<char> >' requested here
  E(e, o->getSrcInfo(), args...);
  ^
../codon/parser/ast/stmt.cpp:627:9: note: in instantiation of function template specialization 'codon::E<char [10], std::__cxx11::basic_string<char> >' requested here
        E(Error::CLASS_CONFLICT_DECORATOR, c, "dataclass", Attr::Tuple);
        ^
In file included from ../codon/parser/ast/stmt.cpp:3:
In file included from .././codon/parser/ast/stmt.h:10:
In file included from .././codon/parser/ast/expr.h:11:
In file included from .././codon/parser/ast/types.h:5:
In file included from .././codon/parser/ast/types/class.h:10:
In file included from .././codon/parser/ast/types/type.h:11:
In file included from .././codon/parser/common.h:17:
In file included from .././codon/util/common.h:13:
.././codon/compiler/error.h:496:74: error: missing default argument on parameter 'args'
void E(Error e, const codon::SrcInfo &o = codon::SrcInfo(), const TA &...args) {
                                                                         ^
3 errors generated.
[3/116] Building CXX object CMakeFiles/codonc.dir/codon/parser/peg/peg.cpp.o
FAILED: CMakeFiles/codonc.dir/codon/parser/peg/peg.cpp.o
/usr/bin/clang++  -Dcodonc_EXPORTS -I../. -I_deps/peglib-src -I_deps/toml-src/include -I_deps/semver-src/include -I_deps/fmt-src/include -pedantic -fvisibility-inlines-hidden -Wno-return-type-c-linkage -Wno-gnu-zero-variadic-macro-arguments -Wno-deprecated-declarations -O3 -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=gnu++17 -MD -MT CMakeFiles/codonc.dir/codon/parser/peg/peg.cpp.o -MF CMakeFiles/codonc.dir/codon/parser/peg/peg.cpp.o.d -o CMakeFiles/codonc.dir/codon/parser/peg/peg.cpp.o -c ../codon/parser/peg/peg.cpp
In file included from ../codon/parser/peg/peg.cpp:3:
In file included from ../codon/parser/peg/peg.h:9:
In file included from .././codon/parser/ast.h:6:
In file included from .././codon/parser/ast/expr.h:11:
In file included from .././codon/parser/ast/types.h:5:
In file included from .././codon/parser/ast/types/class.h:10:
In file included from .././codon/parser/ast/types/type.h:11:
In file included from .././codon/parser/common.h:17:
In file included from .././codon/util/common.h:13:
.././codon/compiler/error.h:496:74: error: missing default argument on parameter 'args'
void E(Error e, const codon::SrcInfo &o = codon::SrcInfo(), const TA &...args) {
                                                                         ^
../codon/parser/peg/peg.cpp:119:7: note: in instantiation of function template specialization 'codon::error::E<std::__cxx11::basic_string<char> >' requested here
      E(error::Error::COMPILER_NO_FILE, SrcInfo(), file);
      ^
1 error generated.
[4/116] Building CXX object CMakeFiles/codonc.dir/codon/parser/visitors/simplify/simplify.cpp.o
FAILED: CMakeFiles/codonc.dir/codon/parser/visitors/simplify/simplify.cpp.o
/usr/bin/clang++  -Dcodonc_EXPORTS -I../. -I_deps/peglib-src -I_deps/toml-src/include -I_deps/semver-src/include -I_deps/fmt-src/include -pedantic -fvisibility-inlines-hidden -Wno-return-type-c-linkage -Wno-gnu-zero-variadic-macro-arguments -Wno-deprecated-declarations -O3 -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=gnu++17 -MD -MT CMakeFiles/codonc.dir/codon/parser/visitors/simplify/simplify.cpp.o -MF CMakeFiles/codonc.dir/codon/parser/visitors/simplify/simplify.cpp.o.d -o CMakeFiles/codonc.dir/codon/parser/visitors/simplify/simplify.cpp.o -c ../codon/parser/visitors/simplify/simplify.cpp
In file included from ../codon/parser/visitors/simplify/simplify.cpp:3:
In file included from ../codon/parser/visitors/simplify/simplify.h:10:
In file included from .././codon/parser/ast.h:6:
In file included from .././codon/parser/ast/expr.h:11:
In file included from .././codon/parser/ast/types.h:5:
In file included from .././codon/parser/ast/types/class.h:10:
In file included from .././codon/parser/ast/types/type.h:11:
In file included from .././codon/parser/common.h:17:
In file included from .././codon/util/common.h:13:
.././codon/compiler/error.h:496:74: error: missing default argument on parameter 'args'
void E(Error e, const codon::SrcInfo &o = codon::SrcInfo(), const TA &...args) {
                                                                         ^
.././codon/util/common.h:149:3: note: in instantiation of function template specialization 'codon::error::E<char [5]>' requested here
  E(e, o->getSrcInfo(), args...);
  ^
../codon/parser/visitors/simplify/simplify.cpp:172:5: note: in instantiation of function template specialization 'codon::E<char [5]>' requested here
    E(Error::UNEXPECTED_TYPE, expr, "type");
    ^
In file included from ../codon/parser/visitors/simplify/simplify.cpp:3:
In file included from ../codon/parser/visitors/simplify/simplify.h:10:
In file included from .././codon/parser/ast.h:6:
In file included from .././codon/parser/ast/expr.h:11:
In file included from .././codon/parser/ast/types.h:5:
In file included from .././codon/parser/ast/types/class.h:10:
In file included from .././codon/parser/ast/types/type.h:11:
In file included from .././codon/parser/common.h:17:
In file included from .././codon/util/common.h:13:
.././codon/compiler/error.h:496:74: error: missing default argument on parameter 'args'
void E(Error e, const codon::SrcInfo &o = codon::SrcInfo(), const TA &...args) {
                                                                         ^
.././codon/util/common.h:141:3: note: in instantiation of function template specialization 'codon::error::E<char [9]>' requested here
  E(e, o->getSrcInfo(), args...);
  ^
../codon/parser/visitors/simplify/simplify.cpp:253:3: note: in instantiation of function template specialization 'codon::E<char [9]>' requested here
  E(Error::UNEXPECTED_TYPE, expr, "ellipsis");
  ^
In file included from ../codon/parser/visitors/simplify/simplify.cpp:3:
In file included from ../codon/parser/visitors/simplify/simplify.h:10:
In file included from .././codon/parser/ast.h:6:
In file included from .././codon/parser/ast/expr.h:11:
In file included from .././codon/parser/ast/types.h:5:
In file included from .././codon/parser/ast/types/class.h:10:
In file included from .././codon/parser/ast/types/type.h:11:
In file included from .././codon/parser/common.h:17:
In file included from .././codon/util/common.h:13:
.././codon/compiler/error.h:496:74: error: missing default argument on parameter 'args'
void E(Error e, const codon::SrcInfo &o = codon::SrcInfo(), const TA &...args) {
                                                                         ^
.././codon/util/common.h:141:3: note: in instantiation of function template specialization 'codon::error::E<char [6]>' requested here
  E(e, o->getSrcInfo(), args...);
  ^
../codon/parser/visitors/simplify/simplify.cpp:258:3: note: in instantiation of function template specialization 'codon::E<char [6]>' requested here
  E(Error::UNEXPECTED_TYPE, expr, "range");
  ^
3 errors generated.
[6/116] Building CXX object CMakeFiles/codonc.dir/codon/parser/visitors/simplify/ctx.cpp.o
FAILED: CMakeFiles/codonc.dir/codon/parser/visitors/simplify/ctx.cpp.o
/usr/bin/clang++  -Dcodonc_EXPORTS -I../. -I_deps/peglib-src -I_deps/toml-src/include -I_deps/semver-src/include -I_deps/fmt-src/include -pedantic -fvisibility-inlines-hidden -Wno-return-type-c-linkage -Wno-gnu-zero-variadic-macro-arguments -Wno-deprecated-declarations -O3 -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=gnu++17 -MD -MT CMakeFiles/codonc.dir/codon/parser/visitors/simplify/ctx.cpp.o -MF CMakeFiles/codonc.dir/codon/parser/visitors/simplify/ctx.cpp.o.d -o CMakeFiles/codonc.dir/codon/parser/visitors/simplify/ctx.cpp.o -c ../codon/parser/visitors/simplify/ctx.cpp
In file included from ../codon/parser/visitors/simplify/ctx.cpp:3:
In file included from .././codon/parser/visitors/simplify/ctx.h:14:
In file included from .././codon/parser/cache.h:11:
In file included from .././codon/cir/cir.h:5:
In file included from .././codon/cir/const.h:5:
In file included from .././codon/cir/module.h:10:
In file included from .././codon/cir/func.h:5:
In file included from .././codon/cir/flow.h:8:
In file included from .././codon/cir/base.h:11:
In file included from .././codon/cir/attribute.h:12:
In file included from .././codon/util/common.h:13:
.././codon/compiler/error.h:496:74: error: missing default argument on parameter 'args'
void E(Error e, const codon::SrcInfo &o = codon::SrcInfo(), const TA &...args) {
                                                                         ^
../codon/parser/visitors/simplify/ctx.cpp:33:5: note: in instantiation of function template specialization 'codon::error::E<std::__cxx11::basic_string<char> >' requested here
    E(Error::ID_INVALID_BIND, getSrcInfo(), name);
    ^
1 error generated.
[7/116] Building CXX object CMakeFiles/codonc.dir/codon/parser/visitors/simplify/assign.cpp.o
FAILED: CMakeFiles/codonc.dir/codon/parser/visitors/simplify/assign.cpp.o
/usr/bin/clang++  -Dcodonc_EXPORTS -I../. -I_deps/peglib-src -I_deps/toml-src/include -I_deps/semver-src/include -I_deps/fmt-src/include -pedantic -fvisibility-inlines-hidden -Wno-return-type-c-linkage -Wno-gnu-zero-variadic-macro-arguments -Wno-deprecated-declarations -O3 -fPIC   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=gnu++17 -MD -MT CMakeFiles/codonc.dir/codon/parser/visitors/simplify/assign.cpp.o -MF CMakeFiles/codonc.dir/codon/parser/visitors/simplify/assign.cpp.o.d -o CMakeFiles/codonc.dir/codon/parser/visitors/simplify/assign.cpp.o -c ../codon/parser/visitors/simplify/assign.cpp
In file included from ../codon/parser/visitors/simplify/assign.cpp:6:
In file included from .././codon/parser/ast.h:6:
In file included from .././codon/parser/ast/expr.h:11:
In file included from .././codon/parser/ast/types.h:5:
In file included from .././codon/parser/ast/types/class.h:10:
In file included from .././codon/parser/ast/types/type.h:11:
In file included from .././codon/parser/common.h:17:
In file included from .././codon/util/common.h:13:
.././codon/compiler/error.h:496:74: error: missing default argument on parameter 'args'
void E(Error e, const codon::SrcInfo &o = codon::SrcInfo(), const TA &...args) {
                                                                         ^
.././codon/util/common.h:141:3: note: in instantiation of function template specialization 'codon::error::E<std::__cxx11::basic_string<char> >' requested here
  E(e, o->getSrcInfo(), args...);
  ^
../codon/parser/visitors/simplify/assign.cpp:78:7: note: in instantiation of function template specialization 'codon::E<std::__cxx11::basic_string<char> >' requested here
      E(Error::ID_NOT_FOUND, ei, ei->value);
      ^
1 error generated.
[11/116] Building CXX object CMakeFiles/codonc.dir/codon/parser/cache.cpp.o
ninja: build stopped: subcommand failed.
tim@sniirm-z001:~/proj/codon$ uname -a
Linux sniirm-z001 5.10.110 #20 SMP Fri Mar 3 15:56:13 CST 2023 aarch64 aarch64 aarch64 GNU/Linux
tim@sniirm-z001:~/proj/codon$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
tim@sniirm-z001:~/proj/codon$

**Comment by inumanag** [comment]
Should be fixed in #604.
