### ISSUE TITLE
Float division output

### ISSUE THREAD

**Issue by nagayev** [exaloop/codon#134]
Code like
```python
a=8/2
print(a)
```
gives 4.0 using python3 and 4 with condon
typeof a is float, by it was printed similar to int

**Comment by inumanag** [comment]
Ho @nagayev 

This is by design: `/` returns float, while `//` returns int. Note that Codon has distinct types for ints (and even for different kinds of ints) and floats, unlike Python: see https://docs.exaloop.io/codon/general/differences for details.
