### ISSUE TITLE
DLL Export support

### ISSUE THREAD

**Issue by sancarn** [exaloop/codon#139]
Codon looks really cool, something I saw which was missing and I can't imagine it would be difficult (i imagine it's natively supported by LLVM) is export to `dll`, commonly used on windows.

**Comment by sancarn** [comment]
Seems like this might have to come post-windows support #69 😅

**Comment by inumanag** [comment]
@sancarn Would this work: https://docs.exaloop.io/codon/interoperability/cpp ? This should work even on Windows AFAIK.

We do not support any Windows-specific features at the moment.

**Comment by sancarn** [comment]
@inumanag Not 100% sure, would have to test, but I suspect the main issue at the moment is the call convention. `.o` files use `cdecl` where as `dll`s use `stdcall`. I'm probably oversimplifying it though 😅 

* https://stackoverflow.com/a/3404412/6302131 - could be handy

**Comment by sancarn** [comment]
@inumanag This is a way to call from C++ yes. My main hope was calling it via  use of [`LoadLibrary`](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya) and [`GetProcAddress`](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getprocaddress?redirectedfrom=MSDN).  Unfortunately I think compilation to `.o` mangles names and is also `cdecl` rather than `stdcall`?

Not sure, would have to test.
