### ISSUE TITLE
import codon in python failed on mac

### ISSUE THREAD

**Issue by srm8998** [exaloop/codon#144]
I tried installing using: CC=clang pip install codon-jit
But still facing import error on Mac.
ImportError: dlopen(/Users/srm/opt/anaconda3/envs/my_ws/lib/python3.7/site-packages/codon/codon_jit.cpython-37m-darwin.so, 0x000A): symbol not found in flat namespace (__ZN5codon3jit13getJITLibraryEv)

**Comment by inumanag** [comment]
Please see #123

**Comment by srm8998** [comment]
Python version: Python 3.7.13
macOS: Monterey os. Version 12.6
