### ISSUE TITLE
Evaluation order of "r" magic methods

### ISSUE THREAD

**Issue by arshajii** [exaloop/codon#145]
``` python
class A:
    def __radd__(self, n: int):
        return 0

def f():
    print('f')
    return 1

def g():
    print('g')
    return A()

f() + g()
```

Python gives `f g` but Codon gives `g f`, probably because Codon transforms this to `A.__radd__(g(), f())` while it should really be transformed to `tmp1 = f(); tmp2 = g(); A.__radd__(tmp2, tmp1)`.

**Comment by inumanag** [comment]
Fixed in #604.
