### ISSUE TITLE
How to call a codon function in python?

### ISSUE THREAD

**Issue by bw-xu** [exaloop/codon#146]
For example, we have a codon file `foo_par.codon`:

```Python
def foo():
    @par(num_threads=5)
    for i in range(10):
        import threading as thr
        print('hello from thread', thr.get_ident())
    return [1, 2, 3]
```

we can build it by `codon build foo_par.codon` and generate a file `foo_par` (in MacOS, for example).

If we want to call the function in python, how to make it?

What I tried is to build the file with `--lib` option

`codon build --lib foo_par.codon`

and got a `foo_par.dylib` file.

To call the `foo` function, I tried the code following

```Python
from ctypes import CDLL

lib = CDLL("par.dylib")

a = lib.foo()
print(a)
```
The output is as the following:

> hello from thread hello from thread hello from threadhello from thread  4
> 2
> hello from thread hello from thread5 
> 4
> hello from thread 3
> hello from thread 3
> 1
> hello from thread 1
> hello from thread 5
> 2
> 73080800

the last line should be `[1, 2, 3]`.

To call a codon function with `CDLL`, it runs well, however, the return value is wrong.

How to fix that? Or is there any other way to call in python the function `foo`?

**Comment by inumanag** [comment]
Using CDLL probably won't work (at least not easily) with complex types (e.g., lists) due to GC and other issues.
I'd suggest using codon.jit decorator here.
