### ISSUE TITLE
Cannot detect attributes added via __init__

### ISSUE THREAD

**Issue by dolfinus** [exaloop/codon#150]
I've tried to run Codon on this source code:
```python
class MyClass:
    def __init__(self, value):
        self.value

MyClass(1)
```

```bash
codon build --release --cost-kind=latency --exe ./1.py
```

But got an error:
```
1.py:3:9-19: error: 'MyClass' object has no attribute 'value'
╰─ 1.py:5:1-11: error: during the realization of __init__(self: MyClass, value: int)
```

Adding attributes in `__init__` method is one of basics of Python, it should not fail.

It can be fixed by:
```python
class MyClass:
    value: int

    def __init__(self, value):
        self.value

MyClass(1)
```

But this creates a class-level attribute which is shadowed by an object-level attribute with the same name (created in `__init__`), which is not great.

**Comment by inumanag** [comment]
Hi @dolfinus 

Currently, Codon classes are equivalent to Python's dataclasses. So the second example will work _as expected_ (those are not class attributes).

Limited support for Python-like `__init__` can be achieved by doing

```
@autodeduce
def __init__(self, value):
   self.value = value
```
