### ISSUE TITLE
codon type checking error

### ISSUE THREAD

**Issue by learnforpractice** [exaloop/codon#151]
It sounds like Codon doesn't correctly check some types.

test.codon
```
class A(object):
        a: Array[byte]
        pos: int
        def __init__(self, ptr: Ptr[byte], len: int):
                self.a = Array[byte](ptr, len)
                self.pos = 0


# wrong type
a = A(Array[byte](10), 10)

# correct type
#a = A(Ptr[byte](10), 10)

print(a.pos)
assert a.pos == 0
```

output:

```
10
AssertionError: Assert failed (test.codon:11)

Raised from: 
test.codon:11:1

Backtrace:
  [0x10aef5bd4] main.0 at test.codon:11:1
Abort trap: 6
```

**Comment by arshajii** [comment]
This is because Codon adds a default constructor that takes all the fields as arguments:

``` python
    # implicitly generated
    def __init__(self, a: Array[byte], pos: int):
        self.a = a
        self.pos = pos
```

This should definitely be documented though.

**Comment by learnforpractice** [comment]
That makes sense, but I believe it would be better to avoid creating a default constructor that takes arguments. It goes against developer intuition, can lead to confusion, and violates the principle of **Explicit is better than implicit**.

**Comment by learnforpractice** [comment]
Suggest using a @default decorator for generating the default constructor.

**Comment by inumanag** [comment]
You can disallow this by doing `@dataclass(init=False)` (by default, it's true).

**Comment by learnforpractice** [comment]
Thanks. Obviously, it's more convenience to set `init` to True by default, however, this can lead to confusion for developers who are unaware of the default behavior

**Comment by arshajii** [comment]
We were mostly following Python's dataclass semantics, which does this by default. *But* if the user defines their own `__init__` then probably we shouldn't auto-generate one (which would again follow Python)...
