### ISSUE TITLE
 How to compile an imported module file into native code?

### ISSUE THREAD

**Issue by juliuszz** [exaloop/codon#154]
For example, main.py uses "from python import module" to import functions from module.py, and uses codon to build main.py into native code, but module.py is still a python file, not native machine code.
How to compile both module.py and mail.py into native code?
Thx!

**Comment by inumanag** [comment]
Hi @juliuszz 

Codon cannot compile modules loaded through Python bridge: the compilation works only on Codon-hosted code. This is by design: we don't plan to support this in the near future. Nuitka _might_ be the answer you are looking for.

**Comment by hadjebi** [comment]
@inumanag 
What's the workaround for importing other modules, then?
