### ISSUE TITLE
Unsigned short being treated as integer by the compiler

### ISSUE THREAD

**Issue by NT-TNT** [exaloop/codon#163]
Today I've been manually porting the **socket** Python class into Codon.  
For some of the function arguments, I needed to use an unsigned short, so I used `u16(num)` and `Uint[16](num)`, but it keeps being mistaken as an int variable type.  
  
To reproduce the error, make this steps:  
- Create a main.codon file with the following code:
```python
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
```
  
- Create a socket.codon file with the following code:
```python
AF_INET   = u16(2)
SOCK_STREAM    = u16(1)
class socket:
	__family: u16
	__type: u16
	__proto: u16
	__fileno: u16
	__host: str
	__port: u16

	def __init__(self, family: u16 = AF_INET, type: u16 = SOCK_STREAM, proto: u16 = 0, fileno: u16 = None):
		self.__family = family
		self.__type = type
		self.__proto = proto
		self.__fileno = fileno 
```
  
The error will be raised when executing main.codon file:
```bash
tnt@Mac-Studio socket % codon run main.codon
main.codon:9:5-47: error: 'int' does not match expected type 'UInt[16]'
```
  
However, the code seems to work flawlessly when using unsigned shorts, like the following line of code:
```python
# socket.codon
from C import htons(u16) -> u16

# main.codon
import socket
port = u16(0xaabb)
print(hex(socket.htons(port)))
```

The output of that is the following:
```bash
tnt@Mac-Studio socket % codon run main.codon
0xbbaa
```
  
I don't think this error it's related to my code, but it could be since I am not 100% familiar at the moment. Anyway, once I finish with this partial socket library, I would wish to submit it to the repository so more people can make use of it. How could I contribute?  
  
Oh, and one question! Is `str.from_ptr(hostname)` supposed to be used? Or it could change in future versions so it is not supposed to be used? I am actually using it in the `gethostname()` function.

**Comment by arshajii** [comment]
Hi @NT-TNT -- the error is from `proto: u16 = 0`, which should be ` proto: u16 = u16(0)` (since there isn't an implicit conversion from `int` to `u16`).

`str.from_ptr()` is completely fine to use as well (in general only some things named with a leading `_` might be changed in backwards-incompatible ways).

And we would definitely welcome a pull request! Feel free to submit one and we'll review it.

**Comment by arshajii** [comment]
Oh, also for `fileno: u16 = None`: I'm assuming the type should be `Optional[u16]` (same with the `__fileno` field)?

**Comment by NT-TNT** [comment]
Oh thank you so much! I didn't thought about it and it was so obvious. I'm closing the issue!
