### ISSUE TITLE
It's a w ssome

### ISSUE THREAD

**Issue by drivenow** [exaloop/codon#167]

**Comment by drivenow** [comment]
It's awesome that codon has similar syntax like python and powerful performance. 

I have a question that whether codon supports some common python  features or not? For example coroutine relevant, like asyncio IO, or the usage of yield?

Of course codon can integrate python code  just like the exaloop doc shows, but how does this work and will this influence performance?

**Comment by arshajii** [comment]
Hi @drivenow -- you can check the [docs](https://docs.exaloop.io/codon/) under "language" to see the kinds of the things that are supported. `yield` is supported; async I/O not yet but we plan to incorporate it in a future version.

As for using external Python code/libraries: these will be executed by the regular Python interpreter so will have the same performance. Please let me know if you have any other questions. :)
