### ISSUE TITLE
Basic attributes don't work

### ISSUE THREAD

**Issue by markshannon** [exaloop/codon#168]
The following code doesn't work.
```
class C:
     
     def __init__(self):
         self.e = None
     
c = C()
print(c.e)
```
`codon run test.py`
produces the following error message:
```
test_codon.py:4:10-14: error: 'C' object has no attribute 'e'
╰─ test_codon.py:6:5-8: error: during the realization of __init__(self: C)
```

**Comment by arshajii** [comment]
Discussed in #150: currently Codon needs to know the attributes for the class, but we do have automatic detection of them implemented and will be incorporating it soon.
