### ISSUE TITLE
Division by zero should raise an exception.

### ISSUE THREAD

**Issue by markshannon** [exaloop/codon#173]
Both `1.0/0.0` and `1/0` should raise a `ZeroDivisionError`
Codon produces `inf`

**Comment by learnforpractice** [comment]
As mentioned here: https://docs.exaloop.io/codon/general/releases#semantics
Add `-numerics=py` option will raise ZeroDivisionError
```
codon build -numerics=py ...
```

**Comment by markshannon** [comment]
Why is incorrect behavior the default?

**Comment by learnforpractice** [comment]
I have the same question as you. But I think the Codon team prioritizes performance above all else.

**Comment by markshannon** [comment]
Including correctness, apparently.

**Comment by arshajii** [comment]
The docs linked above and also ["Differences with Python"](https://docs.exaloop.io/codon/general/differences) describe this. We won't be changing this right now.
