### ISSUE TITLE
Recursive inner functions do not work

### ISSUE THREAD

**Issue by jordi-petit** [exaloop/codon#189]
Hello!

Recursive inner functions do not work. With this program:

```python
def f(x: int) -> int:
    z = 2 * x

    def g(y: int) -> int:
        if y == 0:
            return 1
        else:
            return g(y - 1) * z
    return g(4)


print(f(3))
```

codon  0.15.4 produces this error:

```
p.py:8:20-28: error: g() missing 1 required positional argument: 'z.2.1'
├─ p.py:9:12-16: error: during the realization of g(y: int, z.2.1: int)
╰─ p.py:12:7-8: error: during the realization of f(x: int)
```

It looks like the compiler was expecting the captured local variable as a second parameter for`g`. Indeed, using `return g(y - 1, z) * z` "works". 

Also, if `g` does not use recursion or the local `z` is removed, the program compiles without problem.

**Comment by inumanag** [comment]
Thank you--- this is indeed a bug in the capture handling. Will provide a fix shortly.

**Comment by jordi-petit** [comment]
Thanks for addressing it!

By the way, will closures (ie, returning inner functions with captures) be supported?

**Comment by inumanag** [comment]
That should be already there. Please let me if you encounter any issues with it.
