### ISSUE TITLE
Large bit integers don't appear to be working

### ISSUE THREAD

**Issue by L1nkus** [exaloop/codon#190]
Hey there,

```
m = UInt[2048](1000000000000000)
m *= UInt[2048](10000000000000000)
m //= UInt[2048](10000000000000000)
print(m)
# -4570789518076018688

m2 = UInt[256](1000000000000000)
m2 *= UInt[256](10000000000000000)
m2 //= UInt[256](10000000000000000)
print(m2)
"""
JIT session error: Symbols not found: [ __udivei4 ]
Failure value returned from cantFail wrapped call
Failed to materialize symbols: { (main, { main }) }
UNREACHABLE executed at /github/workspace/llvm/include/llvm/Support/Error.h:786!
Aborted (core dumped)
"""
```

Codon 0.15.4
Python 3.10

**Comment by inumanag** [comment]
Division and modulus are not supported when N > 128 due to LLVM limitations: might be fixed in later versions (https://discourse.llvm.org/t/rfc-add-support-for-division-of-large-bitint-builtins-selectiondag-globalisel-clang/60329). For now, I added a compiler error on such cases for better error reporting.

**Comment by L1nkus** [comment]
Ok, good to know. But apart from division, just printing after multiplying signifies an overflow.
```
m = Int[2048](1000000000000000)
m *= Int[2048](10000000000000000)
print(m)
# -4570789518076018688 
```

**Comment by inumanag** [comment]
Currently, printing casts everything to i64. You can implement your own print for now. We have basic support for this in works, though— should be merged rather soon-ish.

**Comment by L1nkus** [comment]
Cool, thanks.
Though actually, how would one implement an own print for > i128, if division isn’t allowed?

**Comment by inumanag** [comment]
Division is not allowed, but bitshift operators should work.

**Comment by L1nkus** [comment]
> Division is not allowed, but bitshift operators should work.
> […](#)

Sure, but would one print in base 10 and not 2?

**Comment by arshajii** [comment]
@L1nkus Here is an example of doing this for `UInt` in base-10 with just shifts:

``` python
def uint_str(n: UInt[N], N: Static[int]) -> str:
    self_cp = n
    int_str = ''
    while self_cp:
        remainder = 0
        quotient = UInt[N](0)
        # Euclidean division
        for bit_idx in range(N - 1, -1, -1):
            mask = int((self_cp & (UInt[N](1) << UInt[N](bit_idx))) != UInt[N](0))
            remainder = (remainder << 1) + mask
            if remainder >= 10:
                quotient = (quotient << UInt[N](1)) + UInt[N](1)
                remainder -= 10
            else: quotient = quotient << UInt[N](1)
        int_str = str(remainder) + int_str
        self_cp = quotient
    return int_str if int_str else '0'

n = UInt[1000](0x7fffffffffff4321)
print(uint_str(n * n * n))
# 784637716923322755734931432243910842530738091050992112993
```

(Credit to @HarisSmajlovic for the code; we'll likely add this to the standard library soon.)
