### ISSUE TITLE
Doesn't work with poetry package manager

### ISSUE THREAD

**Issue by bryaan** [exaloop/codon#199]
Please support venvs created by [poetry](https://python-poetry.org/).  Right now codon cannot find external libraries when using the codon compiler or the annotation.

Should look something like:

```
poetry run codon run main.py
```

**Comment by ryukinix** [comment]
It seems doesn't support external packages at all.. someone used with venv with pip?

**Comment by elisbyberi** [comment]
@ryukinix My previous comment wasn't specifically related to Anaconda. Rather, it was about setting up the CODON_PYTHON environment variable to enable the use of different Python environments.

You can compile existing pure Python libraries (without dependencies on Python C extensions) in Codon. Additionally, Codon allows you to create Python C extensions. https://docs.exaloop.io/codon/interoperability/pyext

**Comment by elisbyberi** [comment]
@bryaan 

> Poetry replaces setup.py, requirements.txt, setup.cfg, MANIFEST.in and Pipfile with a simple pyproject.toml based project format.

After taking a quick look at the Poetry repository, it seems to be using venvs. However, Codon already supports different venvs through the use of the CODON_PYTHON environment variable.  See: https://github.com/exaloop/codon/issues/109#issuecomment-1509936477

**Comment by inumanag** [comment]
Thank you, @elisbyberi!

Yes, that should be the correct answer; if your package manager properly sets `PYTHONHOME` (or, optionally, `PYTHONPATH`), venvs should work. `CODON_PYTHON` just sets up a Python version and does not care about venvs at all.

If neither works, please reopen the issue.
