### ISSUE TITLE
Websocket library compilable by codon

### ISSUE THREAD

**Issue by L1nkus** [exaloop/codon#200]
Hi,

I'm looking to use codon for improving performance of high-rate websocket payload processing.
I'm wondering, is there any websocket implementation working in codon? I think requests isn't part of stdlib, so I guess network stuff isn't well supported yet?

**Comment by arshajii** [comment]
We don't have it in the standard library yet, but I believe one user actually implemented this and posted the code in [the Slack](https://join.slack.com/t/exaloop/shared_invite/zt-1jusa4kc0-T3rRWrrHDk_iZ1dMS8s0JQ) (not sure of their GitHub username, but they are `@nt_tnt` on Slack). Maybe you can adapt this for your use case?

[Here](https://gist.github.com/arshajii/1cada04c797263f99fe3a446d5b9c1af) is a Gist with the code for convenience (note that there are 3 files there, indicated with comments).

**Comment by frankrap** [comment]
I saw your question about WebSocket support in Codon. Coincidentally, I have recently implemented a WebSocket module for my own project. I have published the code at the following link:

[websocket.py](https://github.com/coinrust/cquant/blob/main/internal/websocket.py)

It is still a work in progress, but it provides basic functionality for WebSocket connections and message handling. Please feel free to check it out and adapt it for your use case if it's helpful. I'm also happy to answer any questions you may have about my implementation.

**Comment by inumanag** [comment]
Merging into #608 .
