### ISSUE TITLE
print(~1) assert

### ISSUE THREAD

**Issue by jplevyak** [exaloop/codon#206]
print(~1)

produces:

Assert failed:  type not set for (unary "~" (int* 1 #:type "int")) [x.py:1:1]
Expression:     expr->type
Source:         /home/jplevyak/projects/codon/codon/parser/visitors/typecheck/typecheck.cpp:63
Aborted (core dumped)

**Comment by arshajii** [comment]
Thanks for the report; "constant expressions" are evaluated in the parser/type checker so I imagine there's some bug with `~` there. We'll fix it ASAP.

**Comment by inumanag** [comment]
Fixed in #23. Thank you for reporting it!
