### ISSUE TITLE
unexpected expression in class definition

### ISSUE THREAD

**Issue by jplevyak** [exaloop/codon#207]
```
class A:
    x = 2
    print(x)


print(A().x)
```

It does not like the print(x) statement in the class definition.

**Comment by inumanag** [comment]
This behaviour is by design: all class slots and variables must be followed by a type. `ClassVar` type is used to distinguish class variables from object members. No other expressions are allowed in the class definition.

This should work:
```
class A:
   x: ClassVar[int] = 2
print(A().x)
```
