### ISSUE TITLE
Inheritance oddness

### ISSUE THREAD

**Issue by jplevyak** [exaloop/codon#208]
```
class A:
    n = 2
class B(A):
    o = 3
print(B().n)
```
python3 produces '3'  while codon produces: error: 'B' object has no attribute 'n'

If I rewrite it as:

```
class A:
    def __init__(self):
        self.n = 2
class B(A):
    def __init__(self):
        A.__init__(self)
        self.o = 3
print(B().n)
```

codon produces:

y.py:3:9-13: error: 'A' object has no attribute 'n'
├─ y.py:6:9-25: error: during the realization of __init__(self: A)
╰─ y.py:8:7-12: error: during the realization of __init__(self: B)

**Comment by inumanag** [comment]
Please see #211 for the explanation and #606 to track the implementation progress.
