### ISSUE TITLE
Member variables not working

### ISSUE THREAD

**Issue by jplevyak** [exaloop/codon#211]
```
class A:
  def __init__(self):
    self.x = 3
print(A().x)
```

produces

x.py:3:5-9: error: 'A' object has no attribute 'x'
╰─ x.py:4:7-12: error: during the realization of __init__(self: A)

**Comment by arshajii** [comment]
Currently the class members need to be listed similar to Python's data classes ([docs](https://docs.exaloop.io/codon/language/classes) for reference). We *do* support deducing members right now if you add the `@deduce` annotation on the class (although it's limited to `__init__`); we'll likely update/generalize this in a future version to be more in line with Python.

**Comment by inumanag** [comment]
Please see #606 to track the implementation progress.
