### ISSUE TITLE
Modular arithmetic is wrong

### ISSUE THREAD

**Issue by taqiohr** [exaloop/codon#226]
```
$ cat check.py
print(-2 % 5)
$ python check.py
3
$ codon run check.py
-2
```

**Comment by arshajii** [comment]
Hi @taqiohr -- by default Codon uses C semantics for integer div/mod. You can get Python semantics by using the `-numerics=py` flag ([relevant docs](https://docs.exaloop.io/codon/general/differences#numerics)).
