### ISSUE TITLE
Type not set for unary "-" leads to a crash

### ISSUE THREAD

**Issue by xiaxinmeng** [exaloop/codon#231]
The type for unary "-" is not set and it leads to a crash of codon in the code.

test.py
```
- 'importlib',
- 'importlib._bootstrap',
- 'importlib._bootstrap_external',
```

Reproduce:
`codon/codon-linux-x86_64/codon-deploy/bin/codon' run -release test.py`

Crash message:
```
Assert failed:	type not set for (unary "-" (string* ("importlib") #:type "str")) [20824_644122661_2__0.py:2:1]
Expression:	expr->type
Source:		/github/workspace/codon/parser/visitors/typecheck/typecheck.cpp:63
Aborted (core dumped)
```

Environment:
codon: v0.15.5 on Feb 6
Ubuntu 18.04

**Comment by arshajii** [comment]
Thanks for the report; I believe this is the same bug as https://github.com/exaloop/codon/issues/206 -- will fix ASAP.
