### ISSUE TITLE
Deleting not found file leads to crashing

### ISSUE THREAD

**Issue by xiaxinmeng** [exaloop/codon#233]
'f' is not found file. Delele f and then compile the following code. Codon crashes. 

test.py: 
```
f = open('path')
f.write('data')
del f
```

Reproduce:
codon/codon-linux-x86_64/codon-deploy/bin/codon' run -release test.py

Crash message:
```
IOError: file path could not be opened

Raised from: std.internal.file.File.__init__:2
codon/codon-linux-x86_64/codon-deploy/lib/codon/stdlib/internal/file.codon:17:13
Aborted (core dumped)
```

Behavior on CPython(3.10.8):
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    f = open('path')
FileNotFoundError: [Errno 2] No such file or directory: 'path'
```

Environment:
codon: v0.15.5 on Feb 6
Ubuntu 18.04

**Comment by arshajii** [comment]
Hi @xiaxinmeng -- this is expected behavior; Codon throws an exception and aborts if it propagates out of the program (similar to C++ exceptions). Under the hood it calls [`abort()`](https://en.cppreference.com/w/c/program/abort).
