### ISSUE TITLE
Is there any plan to SUPPORT Linux on arm platform

### ISSUE THREAD

**Issue by Nelson-He** [exaloop/codon#234]
Hi all,
When I tried to install codon by using 
```
 /bin/bash -c "$(curl -fsSL https://exaloop.io/install.sh)"
```
I run into the following problem
```
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/exaloop/codon/releases/download/v0.15.5/codon-linux-aarch64.tar.gz [following]
--2023-03-14 19:38:48--  https://github.com/exaloop/codon/releases/download/v0.15.5/codon-linux-aarch64.tar.gz
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 404 Not Found
2023-03-14 19:38:49 ERROR 404: Not Found.
```
Yeal, I can see from the error message that the package does not exist.
So, Is there any plan to support Linux on arm platform?

**Comment by Hermann-SW** [comment]
Duplicate of:  
https://github.com/exaloop/codon/issues/225

**Comment by Nelson-He** [comment]
Sorry about the duplicate, I have jut searched the `arm` key word. Wrong search method. 
This issue will be closed.
