### ISSUE TITLE
Can Codon support big integer computation directly？Ten thousand positive integers

### ISSUE THREAD

**Issue by ewwerpm** [exaloop/codon#238]
这个Codon，支持直接大整数计算吗？成千上万位的整数乘法。 我已经知道taichi、numba都不直接支持大整数乘法了。

**Comment by arshajii** [comment]
Hi @ewwerpm -- Codon supports larger bit-width integers, as shown in https://docs.exaloop.io/codon/language/extra#arbitrary-width-integers. There's no true arbitrary-width int type in the standard library yet, but it's something that will probably be added in the future.

**Comment by inumanag** [comment]
Duplicate of #235.
