### ISSUE TITLE
Segmentation fault when importing a unknown module from the current directory

### ISSUE THREAD

**Issue by xiaxinmeng** [exaloop/codon#239]
The following code triggers a segmentation fault. If there is not 'logging' module in the current directory, codon crashes.

test.py:
`from . import logging `

Reproduce:
codon/codon-linux-x86_64/codon-deploy/bin/codon' run -release test.py

Crash message:
`Segmentation Fault`

Environment:
codon: v0.15.5 on Feb 6
Ubuntu 18.04

**Comment by imhi98** [comment]
i've got the same issue with building executable file.
LOGGER = logging.getLogger("something")
Assert failed:	cannot find 'LOGGER' [send.py:269:9]
Expression:	f
Source:		/github/workspace/codon/parser/visitors/simplify/ctx.cpp:100
Aborted (core dumped)

**Comment by inumanag** [comment]
Fixed in #604.
