### ISSUE TITLE
Recursively calling a function in "try" branch leads to segfault

### ISSUE THREAD

**Issue by xiaxinmeng** [exaloop/codon#240]
The following code recursively calls function foo() in try branch, then it crashes codon in release mode.

test.py
```
def foo():
     try:
         foo()
     except Exception as e:
     	pass
foo()
```

Reproduce:
codon/codon-linux-x86_64/codon-deploy/bin/codon' run -release test.py

Crash message: Segmentation Fault

Behavior on Python 3.10.8: work well

Environment:
codon: v0.15.5 on Feb 6
Ubuntu 18.04

**Comment by inumanag** [comment]
Hi @xiaxinmeng,

Unlike Python, Codon does not track recursion depth; if there is an infinite recursion, the Codon app will run out of stack memory and crash as a result. This is a desired behaviour (tracking this would add significant runtime complexity IMHO).
