### ISSUE TITLE
Transferring a list into a tuple fails on codon 

### ISSUE THREAD

**Issue by xiaxinmeng** [exaloop/codon#242]
See the following example, we define a function izip, which adopts two lists. In this function, we transfer the list into a tuple, then execute yield operation. Codon fails with this piece of code, while CPython can work well with it.

test.py
```
def izip(*args):
    iters = [iter(obj) for obj in args]
    i = 1
    while i<2:
        yield tuple((next(iters) for iters in iters))
        i = i + 1
x = izip([1, 2], [3, 4])
```

Reproduce:
codon/codon-linux-x86_64/codon-deploy/bin/codon' run -release test.py

Crash Message:
```
Assert failed:	cannot find 'iters.2' [66950_1093668153__0.py:5:47]
Expression:	val
Source:		/github/workspace/codon/parser/visitors/typecheck/access.cpp:40
Aborted (core dumped)
```

Behavior on CPython 3.10.8:
work well

Environment:
codon: v0.15.5 on Feb 6
Ubuntu 18.04

**Comment by inumanag** [comment]
Lists cannot be transformed into tuples (tuple size must be known at the compile-time; see https://docs.exaloop.io/codon/general/differences for details).

You can fix this with `yield [next(iters) for iters in iters]`. The assertion failure, though, is fixed in #604.
