### ISSUE TITLE
Returning the position of a null file pointer causes a segfault

### ISSUE THREAD

**Issue by xiaxinmeng** [exaloop/codon#247]
See the following code, f is closed in the 'with' stream. Then we invoke f.tell(). A segfault is reported.

```
with open('x', 'w') as f:
    f.write('xxx')
print(f.tell())
```

Reproduce:
`'codon/codon-linux-x86_64/codon-deploy/bin/codon' run -release test.py`

Crash message:
`Segmentation fault (core dumped)`

Environment:
codon: v0.15.5 on Feb 6
Ubuntu 18.04

**Comment by elisbyberi** [comment]
@arshajii Why we do not call `_ensure_open()`  inside `tell()`, like we do for `write()`, `read()`, `iter()`, etc?https://github.com/exaloop/codon/blob/0bec6e26278fc5f8e6b9fc49ca21ca2b1535df83/stdlib/internal/file.codon#L81

**Comment by arshajii** [comment]
Yes it should be calling `_ensure_open()` -- added it in https://github.com/exaloop/codon/commit/cf57b586067fd408e756708705183f27f0c9b65e. Thanks!
