### ISSUE TITLE
Segmentation fault when taking a lambda function as the value of a dictionary

### ISSUE THREAD

**Issue by xiaxinmeng** [exaloop/codon#249]
See the following example, the value of the dictionary is the lambda function. Executing 'test.py' and codon crashes.

test.py:
`x = {t: lambda x: t * t for t in range(5)}`

Reproduce:
'codon/codon-linux-x86_64/codon-deploy/bin/codon' run -release test.py

Crash message:
`Segmentation fault (core dumped)`

Behavior on CPython 3.10.8:
`{0: <function <dictcomp>.<lambda> at 0x7fb7b38749a0>, 1: <function <dictcomp>.<lambda> at 0x7fb7b38756c0>, 2: <function <dictcomp>.<lambda> at 0x7fb7b3875760>, 3: <function <dictcomp>.<lambda> at 0x7fb7b3875800>, 4: <function <dictcomp>.<lambda> at 0x7fb7b38758a0>}
`

Environment:
codon: v0.15.5 on Feb 6
Ubuntu 18.04

**Comment by arshajii** [comment]
Thanks for the report; this is causing a crash in the parser / front-end. Will fix ASAP.
