### ISSUE TITLE
basic usage

### ISSUE THREAD

**Issue by tedx** [exaloop/codon#260]
On a RHEL 9 system I run some python code and it works fine. I installed codon. When I run:
codon build --release -exe [my python script]
[my python script]:4:8-17: error: no module named 'traceback'
[my python script]:5:8-17: error: no module named 'pyinotify'
[my python script]:6:8-15: error: no module named 'selinux'
[my python script]:8:8-16: error: no module named 'psycopg2'
[my python script]:9:6-14: error: no module named 'psycopg2'
[my python script>]:10:8-11: error: no module named 'pwd'
[my python script]:11:8-14: error: no module named 'socket'
[my python script]:13:6-12: error: no module named 'base64'
[my python script]:13:6-12: error: no module named 'base64'
[my python script]:14:8-15: error: no module named 'hashlib'
[my python script]:15:6-23: error: no module named 'Cryptodome.Cipher'
[my python script]:16:8-12: error: no module named 'json'
[my python script]:18:6-13: error: no module named 'systemd'
[my python script]:19:8-13: error: no module named 'errno'
[my python script]:23:8-32: error: cannot import name 'modules' from 'sys'
[my python script]:33:8-36: error: no module named 'pwd'
[my python script]:37:12-21: error: name 'b64decode' is not defined
....

What do I do? I tried setting PYTHONPATH but no joy. Python 3.9 and all of these modules are installed from official rpms.

**Comment by arshajii** [comment]
Hi @tedx -- Codon currently doesn't support some parts of the Python standard library natively, but you can import these modules using `from python import`, e.g. `from python import hashlib`; then they should work as usual.

**Comment by inumanag** [comment]
Yes, please refer to https://docs.exaloop.io/codon/general/differences and https://docs.exaloop.io/codon/interoperability/python for more details.
