### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by jschwar313** [exaloop/codon#266]
When will codon be supported under windows?  Are there plans for this?

**Comment by HenrYxZ** [comment]
I'm trying to use it in Ubuntu inside Windows through WSL2 but it says:

```
Command 'codon' not found, did you mean:

  command 'codonw' from deb codonw (1.4.4-4)

Try: sudo apt install <deb name>
```

I tried opening and closing the terminal and even rebooting my PC

**Comment by jschwar313** [comment]
This issue is asking for support on a Windows machine running python, not windows running a UNIX version.

**Comment by xlbljz** [comment]
I guess windows is total different from linux. It may need much more work to do.

**Comment by TemporalClepsydra** [comment]
what exactly in the code would need to be changed?

**Comment by elisbyberi** [comment]
Marking as duplicate of #69

**Comment by inumanag** [comment]
See #69.
