### ISSUE TITLE
Add codon benchmark vs python in the README.md file

### ISSUE THREAD

**Issue by Adibov** [exaloop/codon#267]
Adding a benchmark to the _README.md_ file would be a good idea. Since the first thing that will bring up to people's minds after reading the introduction part is to compare its performance with python. A practical benchmark would be [this](https://programming-language-benchmarks.vercel.app/codon-vs-python).

**Comment by arshajii** [comment]
Thanks for the suggestion, @Adibov! We do have a link to a set of benchmarks at the top of the README, but I'll also take a look at the link you included and see about incorporating it.

**Comment by Adibov** [comment]
Oh my bad, didn't see that :))

Nice benchmark btw 👍
