### ISSUE TITLE
ModuleNotFoundError - after fresh install

### ISSUE THREAD

**Issue by pythonmobile** [exaloop/codon#277]
I use asdf on Ubuntu. I ran the installer, and have codon in path (codon run works). But I can not import codon.

```
uname@dual1:~$ which python3
/home/uname/.asdf/shims/python3
uname@dual1:~$ python3 -m codon
/home/uname/.asdf/installs/python/3.10.6/bin/python3: No module named codon
```

Any ideas how to fix this? Using conda is not an option for me. I use pyenv on mac m1 , and have a similar issue on that machine as well. Thanks.

On mac doing

```
$ python3 -m pip install condon-jit
```

solved the import issue. On Ubuntu with Python 3.10.6, I get : 
```
$ python3 -m pip install condon-jit
ERROR: Could not find a version that satisfies the requirement condon-jit (from versions: none)
ERROR: No matching distribution found for condon-jit
```

**Comment by inumanag** [comment]
Hi @pythonmobile 

You are correct: you need to install `codon-jit` for the Python decorator to work.

Please note that you did `python3 -m pip install condon-jit` on Ubuntu instead of `python3 -m pip install codon-jit`. Can you please change `condon` to `codon` and see if it works?
