### ISSUE TITLE
"unexpected dedent" at declaration of async method

### ISSUE THREAD

**Issue by davidmcnabnz** [exaloop/codon#278]
Hi all,  at my first try of codon, compilation failed with 'unexpected dedent' error.  Here's a simplified paraphrase of the code:
```
class Foo(Bar):
    if SERVICE_MODE == SERVICE_MODE_WHATEVER:
        needCorpDb = False
    def __init__(self):
        controls = Controls(CONTROLS_SET)
        super().__init__(controls)
        ... other stuff ...

    async def initialise(self):  # <<<< THIS IS WHAT CODON CALLS 'unexpected dedent'
        await super().initialise()
        ... other stuff ...
```
The same code runs perfectly ok with CPython.

Am I missing something?

Cheers
David

**Comment by arshajii** [comment]
Hi @davidmcnabnz -- Codon doesn't yet support `async`, but we intend to add it in a future release (see https://github.com/exaloop/codon/issues/71).

**Comment by inumanag** [comment]
Moving this to #71.
