### ISSUE TITLE
codon build prime.py fails with: error: process for 'gcc' exited with status 255

### ISSUE THREAD

**Issue by cvmiller** [exaloop/codon#281]
Running on Linux Debian Bullseye. Installed the pre-built binary (v0.15.5) as per the github page.

I can successfully run the example program for primes (I called it prime.py) with the command:

```
$ codon run prime.py 99
25
```

However, I can not build an executable with the command:

```
$ codon build   prime.py 
error: process for 'gcc' exited with status 255
```

Any insight on how to dig out more info on the failure?

**Comment by arshajii** [comment]
Hi @cvmiller -- which version of gcc is on your system (you can check with `gcc --version`)? I'm wondering if this is due to an older gcc version.

**Comment by cvmiller** [comment]
Well, this is a little embarrassing. `gcc` was not installed on the machine. So I have installed it, and now I am getting this error:

```
$ codon build   prime.py 
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
error: process for 'gcc' exited with status 1
```

Is there something else I need to install?

thanks,

**Comment by NickDatLe** [comment]
This works for me but I'm on macos
![image](https://user-images.githubusercontent.com/30253913/227656415-f64904b8-cf9c-4ff8-90f2-4072c0b8f765.png)

**Comment by cvmiller** [comment]
For the record, I am using gcc on Linux (Debian Bullseye), and my (installed today gcc)

```
$ gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by arshajii** [comment]
@cvmiller Can you try installing zlib, i.e. `apt install zlib1g-dev`?

**Comment by cvmiller** [comment]
Thanks! That did the trick. Now I can build an image (and run it). Now I can see how much faster it is. Thanks again.
