### ISSUE TITLE
error: process for 'gcc' exited with status 255

### ISSUE THREAD

**Issue by GoliTech** [exaloop/codon#291]
when I want to use :
"codon build -release -exe test.py "
I get the error:
"error: process for 'gcc' exited with status 255"

**Comment by arshajii** [comment]
Hi @Goli-git, this seems to be similar to https://github.com/exaloop/codon/issues/281 -- can you please check if gcc is installed on your system, for example with `gcc --version`?

**Comment by Goli-git** [comment]
@arshajii sorry for the late reply.
that was the first error and I installed the gcc. 
now I got:
/usr/bin/ld: cannot find -lz: No such file or directory
collect2: error: ld returned 1 exit status
error: process for 'gcc' exited with status 1

**Comment by inumanag** [comment]
You will need to install the zlib packages (`apt install zlib1g-dev` on Debian/Ubuntu/WSL or `dnf install zlib-devel` on Fedora/CentOS/RHEL) to create the executables.
