### ISSUE TITLE
json.dump gives "'File' object has no attribute '__to_py__'" error

### ISSUE THREAD

**Issue by NickDatLe** [exaloop/codon#292]
Here is my simple code file:

```
from python import json

with open('data.json', 'w') as f:
    json.dump([1, 2, 3], f)
```

And here is the error: 

<generated>:661:661: error: 'File' object has no attribute '__to_py__'
├─ python.codon:644:19-35: error: during the realization of __to_py__(self: Tuple[List[int],File])
╰─ test_codon.py:4:5-28: error: during the realization of __call__(self: pyobj, *args: Tuple[List[int],File], **kwargs: KwTuple.N0)

Am I doing anything wrong?

**Comment by elisbyberi** [comment]
@NickDatLe You have to open file in Python.
```
from python import json
from python import io

with io.open('data.json', 'w') as f:
    json.dump([1, 2, 3], f)
```

**Comment by NickDatLe** [comment]
ok that works, thanks!
