### ISSUE TITLE
@par inside .py @codon.jit function

### ISSUE THREAD

**Issue by pjcrosbie** [exaloop/codon#301]
a `@par` loop that works inside a codon compiled file fails to compile inside a `.py` file inside a` @codon.jit`, no debug info available, fails with syntax error on line following `@par` decorator. 

is `@par` not available yet in `@codon.jit`? or do I need to do something else to get to work?

```python
import codon

@codon.jit(debug=True)
def is_prime_codon_par(n):
    if n <= 1:
        return False
    @codon.par(schedule='dynamic', chunk_size=10000, num_threads=16)
    for i in range(2, n):
        if n % i == 0:
            return False
    return True
```

```
    for i in range(2, n):
    ^^^
SyntaxError: invalid syntax
```

thanks

**Comment by inumanag** [comment]
Please see https://docs.exaloop.io/codon/interoperability/decorator: Python cannot parse for-loop decorators, hence this ugly hack :(
