### ISSUE TITLE
LLVM ERROR: inconsistency in registered CommandLine options

### ISSUE THREAD

**Issue by jrborbars** [exaloop/codon#302]
Everytime I run compiled codon, this message appears.

: CommandLine Error: Option 'arm-implicit-it' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted (core dumped)

Tryied to compile with-DENABLE_LLVM_SHARED=1, but the message still the same.
Compiled in manjaro on kernel 6.1.11, with llvm-config 15.0.7, gcc 12.2.1.

**Comment by arshajii** [comment]
Hi @jrborbars -- Codon uses a specific version/fork of LLVM found here: https://github.com/exaloop/llvm-project. You can find build instructions here: https://docs.exaloop.io/codon/advanced/build. Please let me know if the issue persists!

**Comment by inumanag** [comment]
Hi @jrborbars ,

I would also suggest against installing our LLVM globally. Use cmake --install llvm-project/build --prefix=llvm-project/install when installing LLVM. Then you can use -DLLVM_DIR=llvm-project/install/lib/cmake/llvm when configuring Codon.

For compiling Codon LL files, you will need to link to `libcodonrt.so` (compiled with Codon) to get the executable.
