### ISSUE TITLE
Importing codon code from python

### ISSUE THREAD

**Issue by NickDatLe** [exaloop/codon#308]
Is it possible to build a codon script to a .dylib or .so file to be imported into python for execution? I didn't see it in the documentation. I did see how to build object files but you cannot import those into python.

**Comment by arshajii** [comment]
We are working on exactly this and plan to release it in the next version!

**Comment by NickDatLe** [comment]
Awesome, thank you!

**Comment by arshajii** [comment]
FYI we just released in v0.16 a "Python extension" build mode that lets you import/use Codon code from Python -- https://docs.exaloop.io/codon/interoperability/pyext has more info. We plan to add a more detailed guide/tutorial soon as well!

**Comment by GenericUser127** [comment]
Can you please share some more details around this? I can not get it to work.

I have two files in the same folder:

fibc.py
```
def fib(n: int):
    return n if n < 2 else fib(n - 1) + fib(n - 2)
```

test.py
```
from time import time
import fibc
import sys

fibNum = 40
if len(sys.argv) > 1:
    fibNum = int(sys.argv[1])
t0 = time()
ans = fibc.fib(fibNum)
t1 = time()
print(f'Computed fib({fibNum}) = {ans} in {t1 - t0} seconds.')

```

I run the command: `codon build -pyext fibc.py` and it outputs `fibc.o`

If I run `python3 test.py`, it seems to just use fib.py because it had no performance improvement.

Can you let me know what I'm doing wrong?

**Comment by mirzaCet** [comment]
@GenericUser127 - There is an example how to bundle so from the object file.
Check test/python/setup.py (i.e. set CODON_DIR and run python3 setup.py build_ext).

**Comment by GenericUser127** [comment]
Thank you @mirzaCet , I was able to get it working with your push in the right direction.

I'm not sure if it was just something I misunderstood or if its not clear, but I thought I had the option to use just the command line (`codon build -pyext fibc.py`) and the setup tools was an alternative method, but looking now the setup tools also generates the shared object which the command line doesn't.

**Comment by ghuls** [comment]
I wrote a small script that allows you to create a python extension module on Linux without setuptools:

```
$ cat codon_pyext
#!/bin/sh

CODON_PATH="/software/codon/codon-0.18.1";
LD="${LD:-ld}";


codon_pyext () {
    if [ ${#@} -lt 1 ] ; then
        printf "Usage: codon_pyext myext.codon [release|debug]\n";
        return 1;
    fi

    local extension_source="${1}";
    local extension_dir="$(dirname "${extension_source}")";
    local extension_name="${extension_source%.codon}"
    extension_name="${extension_name%.py}"
    extension_name="${extension_name##*/}"

    local extension_object_file="$(tempfile -p "${extension_name}_" -s '.o')"

    local extension_library_file="${extension_dir}/${extension_name}.so"

    case "${2}" in
        release)
            local optimization="--release";;
        debug)
            local optimization="--debug";;
        *)
            local optimization="--debug";;
    esac


    "${CODON_PATH}/bin/codon" build ${optimization} --relocation-model=pic -pyext -o "${extension_object_file}" -module "${extension_name}" "${extension_source}" || return 1;

    "${LD}" -o "${extension_library_file}" "${extension_object_file}" -shared -l codonrt -L "${CODON_PATH}/lib/codon" -rpath "${CODON_PATH}/lib/codon" || return 1;

    rm "${extension_object_file}";

    return 0
}


codon_pyext "${@}"
```

```
./codon_pyext fib.codon release
```

@arshajii Can the start of https://docs.exaloop.io/codon/interoperability/pyext be updated to include the `--relocation-model=pic` part and to include a linker line? As of now it is seems like `codon build -pyext extension.codon` would be enough to create a python extension, which is not the case.
