### ISSUE TITLE
stdlib: xml.etree.ElementTree

### ISSUE THREAD

**Issue by imgurbot12** [exaloop/codon#314]
Hello, I love this project so far and I'm hoping to use it for my own projects but so far the lack of existing standard library modules makes it difficult to integrate with most existing code bases. One of the primary libraries that I use and gets used by many other important libraries are the [xml tools](https://docs.python.org/3/library/xml.etree.elementtree.html).

I would be happy to contribute on helping build out the xml stdlib but it's primarily backed by a cpython parser called `pyexpat` which is just imported [here](https://github.com/python/cpython/blob/3.11/Lib/xml/parsers/expat.py).

Is there a way to include cpython components to allow for the build of this library or what's the best alternative and approach for implementation?

**Comment by imgurbot12** [comment]
I suppose I could, but that sort of defeats the purpose of the project, as you mentioned. My hope is to improve the performance of my code base, but if the majority of the libraries I use are still in native python, there isn't much opportunity for improvement.

Appreciate the suggestion nonetheless. Thanks

**Comment by imgurbot12** [comment]
That sounds less than ideal. Doesn't that just mean importing it directly is an even worse idea? Lol

**Comment by imgurbot12** [comment]
So it sounds like the best alternative would be to write an xml parser from scratch and include it as part of a new version of the standard library?

**Comment by imgurbot12** [comment]
I have a very basic tokenizer complete, working on building out a complete parser. My intention is to first build it in standard python and then convert it to use codon's extra features, but I have quite a few questions about implementation.

First, is there a way to implement C-Like (or perhaps even better Rust-Like) Enums in python with Codon?

Second, I noticed that the [typing](https://github.com/exaloop/codon/blob/develop/stdlib/typing.codon) library is completely empty. I couldn't find any docs related to the `Optional` type. Is there support for the `<type> | None` syntax?

Last, I noticed in the docs that there weren't many instances where a return type was explicitly declared. It seems pretty obvious that whatever compilation is going on infers the type based on the code and what it returns, but will it be able to handle
processing a type with multiple returns? Is there even a reason or advantage to explicitly stating the return?

**Comment by imgurbot12** [comment]
Good to know thanks for the reference. Progress is steady on the XML lib. I have to build a lexer/parser for XPATH as well for the search features lol.

**Comment by imgurbot12** [comment]
Hello, I tried to begin my port to codon after writing most of the base library, but I came across a few issues I'm not sure how to handle.

First: using references before they're defined within the same file. 
For example:
```python
def get_a():
   return A()
   
class A:
    pass

print(get_a())
```
returns `test.codon:2:11-12: error: name 'A' is not defined`
This same issue occurs when importing a library at bottom of the file to avoid circular imports.
Example:
```python
# file1.codon:
from file2 import func_c

def func_a():
  func_c()
  print('Hello World!')

# file2.codon:
def func_b():
  func_a()

def func_c():
  print('Function C!')

from file1 import func_a
```

Second, I'm not sure how Codon handles strings but the lack of a `bytes` or `bytearray` type makes it difficult to work with them.
Each have their own specific uses separate from a standard string type and the bytearray especially makes it easy to append to like a list while still acting as a standard bytes object.

At the moment, these two things are keeping me from progressing any further on converting the library since I can't compile anything at the moment. Any help or workaround would be appreciated thanks :)

**Comment by imgurbot12** [comment]
The scope parsing from top to bottom seems rather restrictive but I understand that implementing more complicated is likely a difficult process. I'll see if it's possible to reorganize the project to avoid import loops then, but it will become a bit tricky when objects depend or re-use one another.

As for the typehints and bytes/bytearray, I look forward to hearing from you. Thanks!

**Comment by imgurbot12** [comment]
I'm going to close this issue. This project ultimately inspired the creation of my new [pyxml library](https://github.com/imgurbot12/pyxml) which was originally intended to be ported into a codon implementation of the stdlib xml library, but my motivation has waned due to my frustration with codon's lack of proper compatibility with python3's standard type annotations which seem to be mutually exclusive with the way codon operates.

As a massive lover of typehints, my hope was that codon would be taking the existing typehints in all of my projects and making use of the extra information provided to make compiled optimizations on them but that doesn't seem to be the way codon ultimately behaves or what is intended, which is a shame.

Ultimately, anyone is free to take my pure python implementation and use it as a reference or outright use it to implement it into codon's stdlib, but I'm concluding my efforts until typehints are properly supported if that ever happens. Best of luck to the codon team and contributers!

**Comment by arshajii** [comment]
Hi @imgurbot12 — appreciate the feedback, and sorry to hear that. We are still working on closing the gap with Python and there are definitely a few places that need more attention.

If possible could you please let me know what specific things/incompatibilities gave you trouble? I want to see if/how we can address them.

**Comment by arshajii** [comment]
Looking through the repo you linked… I can see a couple cases we don’t have support for yet but overall this definitely looks like the type of thing that *should* work in Codon.

Also mentioning @inumanag so he can take a look.

**Comment by imgurbot12** [comment]
> Hi @imgurbot12 — appreciate the feedback, and sorry to hear that. We are still working on closing the gap with Python and there are definitely a few places that need more attention.
> 
> If possible could you please let me know what specific things/incompatibilities gave you trouble? I want to see if/how we can address them.

@arshajii, thank you for your response. Happy to include some of the things I noticed and had difficulty with during my implementation efforts. I've ranked everything I would consider most important to least in an ordered list:

- `bytes` / `bytearray` builtin types do not exist
- localized imports don not support dot notation eg: `from .local_module import X`
- Topdown only parsing means you cannot reference types before they are defined
  nor can you import a partially initialized module
- `@classmethod` decorator does not exist
- `Iterator` typehint missing
- `Type` typehint missing
- `Self` typehint missing
- `BinaryIO/TextIO` typehints missing
- `Generator` typehint only accepts 1 argument as opposed to python using 3
- `Enum` python stdlib not implemented
- `Any` typehint missing
- Protocol/ABC type missing (maybe that's redundant? - might not be nessesary)

Hope that helps. Thanks again :)
