### ISSUE TITLE
Throws error on lines ending with backslash

### ISSUE THREAD

**Issue by codeisnotcode** [exaloop/codon#317]
A backslash at the end of a line seems to cause codon to throw an error: unexpected dedent. Python does not throw this error. Note that Python allows a backslash after a  comma or a plus sign or the like, where it is obvious from the context that the line is incomplete. Codon does not accept this. Codon's parser should be modified to accept precisely the same syntax as python without throwing a syntax error. There are massive corpuses of python on the web that can be fed in to verify identical syntactic processing.

**Comment by hoosierEE** [comment]
Another parser issue, and not mentioned in the "Differences with Python" part of the documentation:

```
if 'a' in'abc':pass # unexpected '''
if'a' in 'abc':pass # unexpected '''
if 'a'in 'abc':pass # unexpected 'in'
```

All these are valid in Python3.

**Comment by inumanag** [comment]
Thanks for reporting these: will fix them soon!
