### ISSUE TITLE
error: 'XXX' object has no attribute 'XXX'

### ISSUE THREAD

**Issue by starbugs-qurong** [exaloop/codon#320]
I have run the following python program program0.py by codon.

class s234DI58I ():
	D81836891=3.7
	def B99q2s0 ( self , s843oO1 : bool , Cb5pZ943U : bool ) -> bool : 
			Gw1B688 = 25 
			self.D81836891 = Gw1B688 / 3   
if __name__ == '__main__':
	a299d4347 = False
	TFo20a51l = True
	QdNZeb5vb= s234DI58I();
	QdNZeb5vb.B99q2s0(a299d4347,TFo20a51l)
	print(QdNZeb5vb.D81836891)

And it output error message as follows:
codon_program0.py:5:4-8: error: 's234DI58I' object has no attribute 'D81836891'
codon_program0.py:10:2-40: error: during the realization of B99q2s0(self: s234DI58I, s843oO1: bool, Cb5pZ943U: bool)

I hava run it by both python3 and pypy3 and output the following content:
8.333333333333334

The related files can be found in https://github.com/starbugs-qurong/python-compiler-test/tree/main/codon/python_0

**Comment by elisbyberi** [comment]
@starbugs-qurong You must declare class members and their types in the preamble of each class (like you would do with Python's dataclasses). See class [docs](https://docs.exaloop.io/codon/language/classes).
``` python
class s234DI58I:
    D81836891: float = 3.7  # type float
```

**Comment by starbugs-qurong** [comment]
Thank you. It can be compiled and executed in the right way after declaring the types of class members.
