### ISSUE TITLE
error: name 'bytes' is not defined

### ISSUE THREAD

**Issue by starbugs-qurong** [exaloop/codon#324]
I have run the following python program program4.py by codon.

class K10LageT4T (): 
	wW71hQN40 = 0.27
	uLc35tmX = 51
	def l44qbGzqB ( self , jC82Ok77R : bool ) -> bytes : 
			p4t1268OIo = ( self.wW71hQN40 - ( ( ( 7660.04 ) - ( 9705.27 ) ) ) ) ; 
			c251kN35N = self.uLc35tmX  
if __name__ == '__main__':
	m8o6p2957 = False
	sY0UInwL1= K10LageT4T();
	sY0UInwL1.l44qbGzqB(m8o6p2957)
	print(sY0UInwL1.wW71hQN40)
	print(sY0UInwL1.uLc35tmX)

And it output error message as follow:
codon_program4.py:4:47-52: error: name 'bytes' is not defined

I hava run it by both python3 and pypy3 and output the following content:
0.27
51

The related files can be found in https://github.com/starbugs-qurong/python-compiler-test/tree/main/codon/python_4

**Comment by elisbyberi** [comment]
@starbugs-qurong Same as in #322

**Comment by starbugs-qurong** [comment]
Thank you. I have changed "bytes" to "int" in the program based on your suggestions, and the error doesn't occur anymore.
