### ISSUE TITLE
error: during the realization of XXX(self: XXX)

### ISSUE THREAD

**Issue by starbugs-qurong** [exaloop/codon#325]
I have run the following python program program5.py by codon.

class T12Hb789 (): 
	BR280BRF = 90
	def D2z16jwnb8 ( self )  : 
			for wX4214N8 in range ( 1 , 10 , 1 ) :
				self.BR280BRF+=self.BR280BRF  
if __name__ == '__main__':
	UZ6M31H= T12Hb789();
	UZ6M31H.D2z16jwnb8()
	print(UZ6M31H.BR280BRF)

And it output error message as follow:
codon_program5.py:5:5-9: error: 'T12Hb789' object has no attribute 'BR280BRF'
codon_program5.py:8:2-22: error: during the realization of D2z16jwnb8(self: T12Hb789)

I hava run it by both python3 and pypy3 and output the following content:
46080

The related files can be found in https://github.com/starbugs-qurong/python-compiler-test/tree/main/codon/python_5

**Comment by elisbyberi** [comment]
@starbugs-qurong Same as in #320 
``` python
class T12Hb789:
    BR280BRF: int = 90  # type int
```

**Comment by starbugs-qurong** [comment]
Thank you. Same as #320, it can be compiled and executed in the right way after declaring the types of class members.
