### ISSUE TITLE
ValueError: optional is None

### ISSUE THREAD

**Issue by starbugs-qurong** [exaloop/codon#327]
I have run the following python program program8.py by codon.

class x5Kp54Fa6 (): 
	y8oQ6lg = 25
	RC954Ay7 = "96tcJ4G"
	def u137u306 ( self ) -> int : 
			QD31jzVqwcount=0
			while (self.RC954Ay7)==None :
				QD31jzVqwcount=QD31jzVqwcount+1
				if QD31jzVqwcount>2:
					break
				Z07144B6 = ( ( self.y8oQ6lg ) * ( 14 ) ) ; 
if __name__ == '__main__':
	OF059yzM= x5Kp54Fa6();
	OF059yzM.u137u306()
	print(OF059yzM.y8oQ6lg)
	print(OF059yzM.RC954Ay7)

And it output error message as follows:
ValueError: optional is None
Raised from: std.internal.types.optional.unwrap:0
.codon/lib/codon/stdlib/internal/types/optional.codon:80:5
Backtrace:
  GCC_except_table74 at .codon/lib/codon/stdlib/internal/types/optional.codon:80:5
  GCC_except_table74 at codon_program8.py:6:27
  GCC_except_table74 at codon_program8.py:13:2
 (core dumped) .codon/bin/codon run codon_program8.py 

I hava run it by both python3 and pypy3 and output the following content:
25
96tcJ4G

The related files can be found in https://github.com/starbugs-qurong/python-compiler-test/tree/main/codon/python_8

**Comment by elisbyberi** [comment]
@starbugs-qurong Same as in #323

**Comment by starbugs-qurong** [comment]
Thank you. I have changed the program based on your suggestions, and the error doesn't occur anymore.
