### ISSUE TITLE
error: no module named 'X'

### ISSUE THREAD

**Issue by salarshk** [exaloop/codon#331]
Hello,

I have used many frameworks and libraries in my Python code such as numpy, torch, torchvision, and even built-in functions such as format. In the case of using CODON, I faced many errors, such as error: no module named 'numpy',  no module named 'torchvision', and no module named 'format'. Would you please help to solve this problem? Should I do somethings more? I use linux and also python3.6.

Thank you very much.

**Comment by elisbyberi** [comment]
@salarshk See Python integration docs: https://docs.exaloop.io/codon/interoperability/python

**Comment by inumanag** [comment]
For large codebases, you will probably need to do fair amount of patching (e.g. `import X -> from python import X`) for now. We hope to change this in the future, however ATM manual handling is needed. 

I'd rather suggest using `@codon.jit` for hotspots and slow parts of the code--- integration in that case is much easier.
