### ISSUE TITLE
Assert failed: cannot find imported function

### ISSUE THREAD

**Issue by Esfo** [exaloop/codon#333]
```
Assert failed:	cannot find 'environment' [database.py:4:1]
Expression:	f
Source:		/github/workspace/codon/parser/visitors/simplify/ctx.cpp:100
[1]    240068 IOT instruction (core dumped)  ./codon build -release -llvm main.py
```

the function I'm importing:

```
import lmdb
from functools import partial

environment = partial(lmdb.Environment, subdir=True, readonly=False, metasync=True, sync=True, map_async=False, mode=493, create=True, readahead=True, writemap=True, meminit=True, max_readers=126, max_dbs=99999, max_spare_txns=1, lock=True)
```

```
from database import environment
```

it's not being imported from an installed package, is that the issue or is the import going wrong?

looks like #205 maybe

**Comment by Esfo** [comment]
yeah, why does it do that? i have lmdb installed

do i need to locally build codon for it to recognize this? i'm using the binary atm

**Comment by elisbyberi** [comment]
@Esfo I forgot to reference this issue #331, https://docs.exaloop.io/codon/interoperability/python

**Comment by elisbyberi** [comment]
@Esfo Try running in terminal, before executing codon:
`export CODON_PYTHON=/usr/lib/libpython3.10.so`

**Comment by Esfo** [comment]
yeah i've done that, same output

it gives me the same problems with installed modules as well

**Comment by inumanag** [comment]
The assertion error is a bug. However, I will need a (smaller) example to be able to reproduce it.

**Comment by Esfo** [comment]
there's 4 lines of code in the example, i wish i could get you something smaller but i'm not sure how

**Comment by inumanag** [comment]
If other modules (e.g., `lmdb`) are written in Codon, I will need them. Otherwise, you need to import them via `from python import lmdb`.

**Comment by Esfo** [comment]
interesting! I'm working on an attempt for this now

by any chance is there a list of packages that are written in codon that i don't need to import that way

also it seems i can import a python script as long as its in PYTHONPATH, but do i still need to do `from python` for this?

**Comment by Esfo** [comment]
it compiled the example above after adding the from python stuff.

for my code base at large, i had no luck. its telling me a lot of my variables aren't defined, as well as a python built-in like eval

i guess i'll have to look into this deeper, but that's different problem i suppose. may as well close this.
