### ISSUE TITLE
Is PYTHONPATH recursive? [no module named]

### ISSUE THREAD

**Issue by Rugau** [exaloop/codon#338]
0) `export PYTHONPATH=.`
1) ``codon run entry.py``
2)
```
parser.py:7:8-30: error: no module named 'ljd.bytecode.prototype'
parser.py:8:8-26: error: no module named 'ljd.rawdump.header'
parser.py:9:8-29: error: no module named 'ljd.rawdump.prototype'
parser.py:10:8-26: error: no module named 'ljd.util.binstream'
parser.py:11:6-18: error: no module named 'ljd.util.log'
parser.py:16:23-53: error: no module named 'ljd'
parser.py:17:22-48: error: no module named 'ljd'
parser.py:26:14-41: error: no module named 'ljd'
parser.py:31:19-31: error: name '_read_header' is not defined
parser.py:34:29-35: error: name 'header' is not defined
parser.py:36:19-35: error: name '_read_prototypes' is not defined
parser.py:38:9-17: error: name 'errprint' is not defined
parser.py:42:9-17: error: name 'errprint' is not defined
parser.py:46:9-17: error: name 'errprint' is not defined
parser.py:52:16-22: error: name 'header' is not defined
parser.py:58:12-51: error: no module named 'ljd'
parser.py:73:21-55: error: no module named 'ljd'
parser.py:75:16-60: error: no module named 'ljd'
parser.py:82:27-36: error: name 'prototype' is not defined
```

But ``ljd.bytecode`` is a folder and ``prototype`` a file name.
It is in the same folder as entry.py, and it only works if all .py files were in the same folder.

**Comment by elisbyberi** [comment]
@Rugau The primary purpose of PYTHONPATH is to enable us to import Python code during development, which may not yet have been converted into an installable Python package (see: making a Python package).

Although PYTHONPATH is not directly associated with Codon, you can try the following command to add all modules found in the "src" folder: 
`export PYTHONPATH="$(printf "%s:" /src/*/)"`

**Comment by Rugau** [comment]
> @RugauO objetivo principal do PYTHONPATH é nos permitir importar o código Python durante o desenvolvimento, que pode ainda não ter sido convertido em um pacote Python instalável (consulte: criando um pacote Python).
> 
> Embora PYTHONPATH não esteja diretamente associado ao Codon, você pode tentar o seguinte comando para adicionar todos os módulos encontrados na pasta "src": `export PYTHONPATH="$(printf "%s:" /src/*/)"`

Same problem, ``no module named``.

**Comment by elisbyberi** [comment]
@Rugau This issue is not related to Codon. Please try fixing it in Python.

**Comment by Rugau** [comment]
> @Rugau This issue is not related to Codon. Please try fixing it in Python.

My Steps:

0) Clone https://gitlab.com/znixian/luajit-decompiler
1) `codon run main.py`
2) `no module named ???` errors

The problem is in the codon, the folder structure is correct. 
If I run it with python it works normally.

Can u review it?

**Comment by elisbyberi** [comment]
@Rugau See #142.

You can add "luajit-decompiler" to PYTHONPATH and then refer to https://docs.exaloop.io/codon/interoperability/python for testing purposes. 

Once again, please note that PYTHONPATH is not directly related to Codon.

**Comment by Rugau** [comment]
> @Rugau See #142.
> 
> You can add "luajit-decompiler" to PYTHONPATH and then refer to https://docs.exaloop.io/codon/interoperability/python for testing purposes.
> 
> Once again, please note that PYTHONPATH is not directly related to Codon.

Hmm...., i applyed `@Python` decorator in main.py and build works. (and change ``from python import XXXX``)

But, i can't run...

```
PyError: No module named 'ljd'
Raised from: pyobj.exc_check:0
/mnt/c/codon/codon/stdlib/internal/python.codon:1166:13
Aborted
```

**Comment by Rugau** [comment]
> @Rugau See #142.
> 
> You can add "luajit-decompiler" to PYTHONPATH and then refer to https://docs.exaloop.io/codon/interoperability/python for testing purposes.
> 
> Once again, please note that PYTHONPATH is not directly related to Codon.

i founded a bug.

```
import os
import sys
import ljd.bytecode.prototype
```

```
parser.py:7:8-30: error: no module named 'ljd.bytecode.prototype'
parser.py:8:8-26: error: no module named 'ljd.rawdump.header'
parser.py:9:8-29: error: no module named 'ljd.rawdump.prototype'
parser.py:10:8-26: error: no module named 'ljd.util.binstream'
parser.py:11:6-18: error: no module named 'ljd.util.log'
parser.py:16:23-53: error: no module named 'ljd'
parser.py:17:22-48: error: no module named 'ljd'
parser.py:26:14-41: error: no module named 'ljd'
parser.py:31:19-31: error: name '_read_header' is not defined
parser.py:34:29-35: error: name 'header' is not defined
parser.py:36:19-35: error: name '_read_prototypes' is not defined
parser.py:38:9-17: error: name 'errprint' is not defined
parser.py:42:9-17: error: name 'errprint' is not defined
parser.py:46:9-17: error: name 'errprint' is not defined
parser.py:52:16-22: error: name 'header' is not defined
parser.py:58:12-51: error: no module named 'ljd'
parser.py:73:21-55: error: no module named 'ljd'
parser.py:75:16-60: error: no module named 'ljd'
parser.py:82:27-36: error: name 'prototype' is not defined

```

Ok, codon found ``parser.py``. 

But, look what is defined in parser.py

`import ljd.bytecode.prototype`

This import is not in the ``ljd.rawdump.parser``` folder, it is in the root folder of the project.

How to tell codon to search the root folders of the project too and not the relative folder? 🤔

**Comment by Rugau** [comment]
> > @Rugau See #142.
> > You can add "luajit-decompiler" to PYTHONPATH and then refer to https://docs.exaloop.io/codon/interoperability/python for testing purposes.
> > Once again, please note that PYTHONPATH is not directly related to Codon.
> 
> I founded a bug.
> 
> input.py
> 
> ```
> import os
> import sys
> import ljd.bytecode.prototype
> ```
> 
> ```
> parser.py:7:8-30: error: no module named 'ljd.bytecode.prototype'
> parser.py:8:8-26: error: no module named 'ljd.rawdump.header'
> parser.py:9:8-29: error: no module named 'ljd.rawdump.prototype'
> parser.py:10:8-26: error: no module named 'ljd.util.binstream'
> parser.py:11:6-18: error: no module named 'ljd.util.log'
> parser.py:16:23-53: error: no module named 'ljd'
> parser.py:17:22-48: error: no module named 'ljd'
> parser.py:26:14-41: error: no module named 'ljd'
> parser.py:31:19-31: error: name '_read_header' is not defined
> parser.py:34:29-35: error: name 'header' is not defined
> parser.py:36:19-35: error: name '_read_prototypes' is not defined
> parser.py:38:9-17: error: name 'errprint' is not defined
> parser.py:42:9-17: error: name 'errprint' is not defined
> parser.py:46:9-17: error: name 'errprint' is not defined
> parser.py:52:16-22: error: name 'header' is not defined
> parser.py:58:12-51: error: no module named 'ljd'
> parser.py:73:21-55: error: no module named 'ljd'
> parser.py:75:16-60: error: no module named 'ljd'
> parser.py:82:27-36: error: name 'prototype' is not defined
> ```
> 
> Ok, codon found `parser.py`.
> 
> But, look what is defined in parser.py
> 
> `import ljd.bytecode.prototype`
> 
> This import is not in the ``ljd.rawdump.parser``` folder, it is in the root folder of the project.
> 
> How to tell codon to search the root folders of the project too and not the relative folder? 🤔 I actually find that when the parser accesses `parser.py`, it searches the import based on the directory it is in, not the root directory of the project. This is why the error occurs.

Yep, it's a codon bug.

See this file and test it:

`b.py:1:8-9: error: no module named 'c'`

[folders_bug.zip](https://github.com/exaloop/codon/files/11181989/folders_bug.zip)

**Comment by Rugau** [comment]
#339
