### ISSUE TITLE
could not support file operation in python

### ISSUE THREAD

**Issue by fzwwj95** [exaloop/codon#341]
I use the code " with open (...) as file: "
codon could not support and report an error : " error: syntax error ,unexpected 'as'  "

**Comment by elisbyberi** [comment]
@fzwwj95 

Please test this code and let me know what errors you encounter:
``` python
with open('codon.test', 'w') as w:
    w.write('test')

with open('codon.test') as r:
    print(r.read())
```

**Comment by fzwwj95** [comment]
I tested both pieces of code separately, and both gave the same error : " error: syntax error ,unexpected 'as' "

**Comment by elisbyberi** [comment]
@fzwwj95 Did you test it in Python?

**Comment by elisbyberi** [comment]
@fzwwj95 Duplicate of #317
