### ISSUE TITLE
Segmentation fault when calling `super().__init__()` in a subclass with codon 0.16.0

### ISSUE THREAD

**Issue by learnforpractice** [exaloop/codon#346]
codon version: 0.16.0
platform: macOS version 12.6.3

**Issue description:**

When running the code provided, I encountered a segmentation fault with error code 11. The issue appears to be related to the call to `super().__init__()` in the subclass `C`.

**Code:**

```python
# test.codon
class A(object):
    value: u64

    def __init__(self):
        self.value = 0u64

    def get_value(self) -> u64:
        return self.value

class B(object):
    a: A
    def __init__(self):
        self.a = A()

class C(B):
    def __init__(self):
        super().__init__()

    def test(self):
        self.a.get_value()

table = C()
table.test()
```

**Steps to reproduce:**

1. Build the code with `codon build test.codon`
2. Run the compiled code with `./test`

**Expected output:**

No segmentation fault.

**Actual output:**

```
Segmentation fault: 11
```

**Investigation:**

I discovered that the segmentation fault does not occur when I comment out the following lines in class `C`:

```python
def __init__(self):
    super().__init__()
```

It seems that the issue is related to the call to `super().__init__()` in the `__init__` method of class `C`.

The older codon does not have this issue.

**Comment by elisbyberi** [comment]
Class "A" attributes do exist, but they cannot be used:
```
table = C()
print(hasattr(table.a, 'value'))  # True
print(hasattr(table.a, 'get_value'))  # True
table.test()  # Segmentation fault: 11
```

**Comment by arshajii** [comment]
Thanks for the report; will fix ASAP.
