### ISSUE TITLE
Does codon really have multi-threaded programming?

### ISSUE THREAD

**Issue by forrlm** [exaloop/codon#347]
In a normal python project, because of the Global Interpreter Lock (GIL), it will only allow one thread to execute Python code at any one time. This means that in Python, multithreaded programs cannot utilize multiple CPU cores to perform computationally intensive tasks simultaneously. So does this problem also exist when executing multi-threaded scripts through codon? Or, multi-process is the only solution

**Comment by arshajii** [comment]
Hi @forrlm -- yes, Codon is a completely new implementation and does not have a GIL, so it supports real multithreaded programming (more info at https://docs.exaloop.io/codon/advanced/parallel).
