### ISSUE TITLE
How do I build everything in a folder

### ISSUE THREAD

**Issue by ceceayo** [exaloop/codon#350]
I have a folder containing an `__init__.py` and `file1.py` and `file2.py`.
`__init__.py` imports `file1.py` and `file2.py`
`file2.py` imports `file1.py`
How do I compile this into one single shared object?

**Comment by elisbyberi** [comment]
@ceceayo https://docs.exaloop.io/codon/general/intro

`codon build -o foo.o __init__.py`

**Comment by inumanag** [comment]
You need to build a single file that imports/includes (recursively) all other files. If you do not import a file anywhere, it won't get built.
