### ISSUE TITLE
Incorrect error messages when a function returns one value to two variables.

### ISSUE THREAD

**Issue by xiaxinmeng** [exaloop/codon#351]
See the following example, we define a function f(), which returns a dic object l.  When we initialize two variables with the returned value, Codon reports an IndexError instead of the ValueError. 

```
def f(x):
    l = []
    for i in x:
        l.append(x)
    return l

a, b = f('1')
```

The actual output on Codon v0.16.0
```
IndexError: list index out of range

Raised from: std.internal.types.ptr.List._idx_check:0
/home/xxm/Desktop/Codon/codon-linux-x86_64/codon-deploy/lib/codon/stdlib/internal/types/collections/list.codon:364:13
Aborted (core dumped)
```

The expected output (CPython 3.10.8, RustPython 0.2.0):  
```
Traceback (most recent call last):
  File "/home/xxm/Desktop/test.py", line 9, in <module>
    a, b = f('1')
ValueError: not enough values to unpack (expected 2, got 1)
```

Reproduce step: 
> download the Pre-built binaries for Linux 
> Type " codon run --release test.py" in the console.

Environment:
Ubuntu 18.04 
Codon v0.16.0
CPython 3.10.8

**Comment by elisbyberi** [comment]
@xiaxinmeng I believe that happens due to the code simplification process. Maybe it's simplified like this:
``` python
t = f(1)
a = t[0]
b = t[1]  # IndexError
```

**Comment by inumanag** [comment]
Correct. This behaviour will stay as-is; our goal is not to have  1-1 parity with CPython error messages (although we might change the error in this instance to something more readable).
