### ISSUE TITLE
pow() should accept negative int exponent as arguments.

### ISSUE THREAD

**Issue by xiaxinmeng** [exaloop/codon#352]
pow() should accept negative int exponent as arguments. For instance, the following Python code can work well on CPython and other Python interpreters.

test.py 
```
a = pow(2, -3)
print(a)    # it should print 0.125 here
```

The actual output on Codon v0.16.0:
```
ValueError: pow() negative int exponent not supported
Raised from: std.internal.builtin.pow:1
/home/xxm/Desktop/Codon/codon-linux-x86_64/codon-deploy/lib/codon/stdlib/internal/builtin.codon:332:9
Aborted (core dumped)
```

Reproduce step:
> download the Pre-built binaries for Linux
> Type " codon run --release test.py" in the console.

Environment:
Ubuntu 18.04
Codon v0.16.0
CPython 3.10.8

**Comment by raceychan** [comment]
```python
def pow(base: int, exp: int, mod: Optional[int] = None):
    if exp < 0:
        raise ValueError("pow() negative int exponent not supported")

    if mod is not None:
        if mod == 0:
            raise ValueError("pow() 3rd argument cannot be 0")
        base %= mod

    result = 1
    while exp > 0:
        if exp & 1:
            x = result * base
            result = x % mod if mod is not None else x
        y = base * base
        base = y % mod if mod is not None else y
        exp >>= 1
    return result % mod if mod is not None else result
```

**Comment by arshajii** [comment]
The challenge with `pow()` is that it can sometimes return an `int` and sometimes return a `float` based on the sign of the exponent. We could have the return type be `Union[int,float]` but that would complicate things for standard positive-int powers, so we disallow it currently. You can cast the first argument to `float` to get it to work, e.g. `pow(2., -3)` works.
