### ISSUE TITLE
Miscompilation of alpha 'α' in ord() 

### ISSUE THREAD

**Issue by xiaxinmeng** [exaloop/codon#353]
The ord() function in Python returns the Unicode code point of a given Unicode character. In the following case of the character 'α' (Greek lowercase letter alpha), the corresponding code point should be 954. 

test.py
```
print(ord('α'))
print(chr(945))
```

The actual output on Codon v0.16.0:
```
TypeError: ord() expected a character, but string of length 2 found
Raised from: std.internal.builtin.ord:0
/home/xxm/Desktop/Codon/codon-linux-x86_64/codon-deploy/lib/codon/stdlib/internal/builtin.codon:123:9
Aborted (core dumped)
```

The expected output( on CPython 3.10.8):
```
945
α
```

Reproduce step:
> download the Pre-built binaries for Linux
>Type " code run --release test.py" in the console.

Environment:
Ubuntu 18.04
Codon v0.16.0
CPython 3.10.8

**Comment by elisbyberi** [comment]
@xiaxinmeng https://docs.exaloop.io/codon/general/differences

**Data types**
- Integers: Codon's int is a 64-bit signed integer, whereas Python's (after version 3) can be arbitrarily large. However Codon does support larger integers via Int[N] where N is the bit width.
- **Strings: Codon currently uses ASCII strings unlike Python's unicode strings.**
- Dictionaries: Codon's dictionary type does not preserve insertion order, unlike Python's as of 3.6.

**Comment by xiaxinmeng** [comment]
Thanks for the explanation!

**Comment by inumanag** [comment]
Yes, we do not support Unicode at the moment. This is something we plan to address in the future, though: https://docs.exaloop.io/codon/general/roadmap
