### ISSUE TITLE
f-string fails with a format specifier ","

### ISSUE THREAD

**Issue by xiaxinmeng** [exaloop/codon#359]
This test program defines a Python f-string. The colon character (:) is used to specify a format specifier, i.e., ",".  This tells Python to format the number with comma separators for every thousand. So the final result of this f-string is the string "1,000,000".

test.py
```
a = f'{1000000:,}'
print(a)
```
The actual output of Codon v0.16.0
```
ValueError: invalid format specifier: invalid type specifier

Raised from: std.internal.format._format_error:0
/home/xxm/Desktop/Codon/codon-linux-x86_64/codon-deploy/lib/codon/stdlib/internal/format.codon:4:2
Aborted (core dumped)
```
The expected output (CPython 3.10.8):
`1,000,000`

Reproduce step:
> download the Pre-built binaries for Linux
> Type " codon run --release test.py" in the console.

Environment:
Ubuntu 18.04
Codon v0.16.0
CPython 3.10.8

**Comment by inumanag** [comment]
Thank you, this is a bug on our end! Merging with #304.
