### ISSUE TITLE
Metaclasses

### ISSUE THREAD

**Issue by elkarouh** [exaloop/codon#361]
Are there any plans to support metaclasses?
Codon gives syntax error when using class Klass(metaclass=...)

**Comment by msftcangoblowm** [comment]
Can't speak for what codon does or will support.

This is general conversation about Python metaclass.

Recent change occurred, which depreciates metaclass in favor of __init_subclass__

So the codon devs can get away with not supporting metaclasses in favor of __init_subclass__

Metaclasses run into metaclass conflicts that are resolvable, but the syntax is awkward and non-intuitive.

**Comment by inumanag** [comment]
Not yet supported; please see #606  for the current progress.
