### ISSUE TITLE
 error: syntax error, expecting < program>.

### ISSUE THREAD

**Issue by sxs505** [exaloop/codon#362]
I installed codon according to the readme and created the file fib.py. After updating the environment variables I tried to use the command "codon run fib.py", but she got an error: fib.py:1:1: error: syntax error, expecting < program>.
How can I run codon correctly?

**Comment by elisbyberi** [comment]
@sxs505 Try running fib.py in fib.zip. (Github does not allow uploading of *.py files)
[fib.zip](https://github.com/exaloop/codon/files/11290970/fib.zip)

**Comment by sxs505** [comment]
The uncompressed Python file works fine, when I modify it it doesn't run directly. I found that it seems that for Python files, each modification needs to be compressed and uncompressed in order to run with codon. It's a bit unbelievable why this is happening

**Comment by sxs505** [comment]
@elisbyberi.
The uncompressed Python file works fine, when I modify it it doesn't run directly. I found that it seems that for Python files, each modification needs to be compressed and uncompressed in order to run with codon. It's a bit unbelievable why this is happening
