### ISSUE TITLE
[Error] Ellipsis is not supported in codon

### ISSUE THREAD

**Issue by raceychan** [exaloop/codon#364]
The title basically says it all.
The issue is simply and easy to reproduce,
1. create a py file
2. put the Ellipsis(three dots) mark in it
3. execute the file

```python
...
```

```bash
>>> codon run test.py
type.py:33:1-4: error: unexpected ellipsis expression
```

while this maybe the intended behavior(since ellipsis is a python object), this is not yet mentioned in the documents. so I would like to raise this issue up.

**Comment by elisbyberi** [comment]
@raceychan Ellipsis are used in pipes: https://docs.exaloop.io/codon/advanced/pipelines
``` python
def calc(x, y):
    return x + y**2

2 |> calc(3) |> print       # 11; equivalent to calc(2, 3)
2 |> calc(..., 3) |> print  # 11; equivalent to calc(2, 3)
2 |> calc(3, ...) |> print  # 7; equivalent to calc(3, 2)
```

**Comment by raceychan** [comment]
> @raceychan Ellipsis is used in pipes: https://docs.exaloop.io/codon/advanced/pipelines
> 
> ``` python
> 
> def calc(x, y):
> 
>     return x + y**2
> 
> 
> 
> 2 |> calc(3) |> print       # 11; equivalent to calc(2, 3)
> 
> 2 |> calc(..., 3) |> print  # 11; equivalent to calc(2, 3)
> 
> 2 |> calc(3, ...) |> print  # 7; equivalent to calc(3, 2)
> 
> ```

not quite sure if it is the same ellipsis we are talking about. Would you be able to reproduce my example? 
If so, perhaps it only works in codon extended syntax?

**Comment by arshajii** [comment]
Hi @raceychan -- we do plan to add support for this in the near future (as it's needed for e.g. NumPy).

**Comment by raceychan** [comment]
> Hi @raceychan -- we do plan to add support for this in the near future (as it's needed for e.g. NumPy).

Thanks for the quick reply.
If you don't mind would you please give me some clue on where to find the ellipse related source code?

**Comment by elisbyberi** [comment]
@raceychan  The error message `unexpected ellipsis expression` indicates that the ellipsis has been used incorrectly. Although ellipsis literal `...` is supported in Codon, it is not a singleton object yet (like `None`), and it is not supported in extended slicing syntax.

[Ellipsis](https://docs.python.org/3/library/constants.html#Ellipsis)

> The same as the ellipsis literal “...”. Special value **used mostly** in conjunction with extended slicing syntax for user-defined container data types.

**Comment by elisbyberi** [comment]
Marking as a duplicate for future reference. #172

**Comment by arshajii** [comment]
We've added support for this and it'll be available in the next version!
