### ISSUE TITLE
How do I install Codon Jupyter plugin

### ISSUE THREAD

**Issue by NoelJacob** [exaloop/codon#371]
```
> codon jupyter
Jupyter support not included. Please install Codon Jupyter plugin.

```
I didn't even know a plugin system was available.

**Comment by elisbyberi** [comment]
@NoelJacob Have you tried https://docs.exaloop.io/codon/interoperability/jupyter

**Comment by NoelJacob** [comment]
> @NoelJacob Have you tried https://docs.exaloop.io/codon/interoperability/jupyter

Creating the kernel file and choosing it gives the same output that plugin isn't installed.

**Comment by elisbyberi** [comment]
@NoelJacob Sorry, I meant to post this link instead: https://docs.exaloop.io/codon/advanced/build#jupyter-support
Sleep deprivation is taking its toll on me.

**Comment by elisbyberi** [comment]
@arshajii Would it be helpful to include a link to the [jupyter-support](https://docs.exaloop.io/codon/advanced/build#jupyter-support) section in the https://docs.exaloop.io/codon/interoperability/jupyter page?

**Comment by arshajii** [comment]
Thanks -- we'll update these docs soon.

**Comment by NoelJacob** [comment]
It'd be cool if you distribute binaries with Jupyter support

**Comment by dbonner** [comment]
Hi all,
I've absolutely failed to build the Jupyter plugin using the latest source code and following the above instructions diligently.
I was able to build codon from the latest source code with no problem.
Cheers,
Daniel

**Comment by inumanag** [comment]
Duplicate of #152—will track the progress there.
