### ISSUE TITLE
Low performance dict by codon jit

### ISSUE THREAD

**Issue by lilothar** [exaloop/codon#376]
**when I try dict performance, I found that, It is much lower when I using codon jit. I'm also exploring why it produces this result.**
**Is it wrong where it is used, or other reasons?**

```python
import codon
from time import time


def is_prime_python():
    d = {}
    for i in range (0, 100000):
        d[str(i)] = i

    for i in range(0, 50000):
        d[str(i)] = i+1

@codon.jit
def is_prime_codon():
    d = {}
    for i in range(0,100000):
        d[str(i)] = i

    for i in range(0, 50000):
        d[str(i)] = i+1

t0 = time()
is_prime_python()
t1 = time()
print(f'[python] took {t1 - t0} seconds')

t0 = time()
is_prime_codon()
t1 = time()
print(f'[codon]  took {t1 - t0} seconds')
```
the result:
```shell
[python] took 0.01917576789855957 seconds
[codon]  took 0.17638945579528809 seconds
```

**Comment by lilothar** [comment]
@elisbyberi  benchmark is not must， one thing I want to know is why after jit, codon is slower, for that, not only codon, tvm and other python jit tools still have this problem

**Comment by elisbyberi** [comment]
> @elisbyberi benchmark is not must， one thing I want to know is why after jit, codon is slower, for that, not only codon, tvm and other python jit tools still have this problem

`codon.jit` is a [decorator](https://docs.python.org/3/glossary.html#term-decorator) that JIT-compiles the function each time you call it.

**Comment by lilothar** [comment]
@elisbyberi got it, thanks
