### ISSUE TITLE
tuple times integer

### ISSUE THREAD

**Issue by ypfmde** [exaloop/codon#383]
While `(1, 2, 3)*4` and `[1, 2, 3]*4` is valid code giving the expected result in CPython, codon only handles the latter and fails for the former.

**Comment by elisbyberi** [comment]
@ypfmde I am unable to reproduce it.

Codon version 0.16.0:
``` python
print((1, 2, 3)*4)  # (1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3)
print([1, 2, 3]*4)  # [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
```

**Comment by ypfmde** [comment]
Sorry, I was accidentally running Codon version 0.15.5. Indeed, in 0.16.0 things are fine.
