### ISSUE TITLE
Type annotation `def f(a: List[int])` not working in codon.jit decorated function

### ISSUE THREAD

**Issue by ypfmde** [exaloop/codon#389]
The code
```
import codon
@codon.jit
def f(a: List[int]):
    return len(a)
```
raises a `NameError: name 'List' is not defined`, while the same function definition works fine in a pure codon program. Also, other type annotations like `int` work in codon.jit decorated functions. Do I misunderstand something, or is this a bug or missing feature in v0.16.1?

**Comment by elisbyberi** [comment]
@ypfmde See: [#355](https://github.com/exaloop/codon/issues/355#issuecomment-1511157798)
