### ISSUE TITLE
`error: no module named ''` for local Python modules

### ISSUE THREAD

**Issue by netotz** [exaloop/codon#390]
I have the following structure:
```
anpcp/
├─ debugger.py
├─ models/
│  ├─ __init__.py
│  ├─ instance_same_set.py
│  ├─ vertex.py
```
Among other files inside `models/`. `__init__.py` is empty.

In `debugger.py` I have:

```py
from models.instance_same_set import InstanceSameSet
```
Then in `instance_same_set.py` I have:

```py
from models.vertex import Vertex
```

When I try to run `debugger.py` with Codon I get the errors like the following:
```sh
$ codon run debugger.py

instance_same_set.py:4:6-19: error: no module named 'models.vertex'
```

This is similar to #176 but I'm not sure where to set `CODON_PYTHON` in WSL and what to point it to.

Is there a way to compile all the related modules with a single command?

Full repository: https://github.com/netotz/alpha-neighbor-p-center-problem

**Comment by elisbyberi** [comment]
@netotz In Codon, you can import a file from the same directory using a relative path:
`from vertex import Vertex  # Python 2`
`from .vertex import Vertex  # Python 3`
