### ISSUE TITLE
Unexpected errors running vanilla Python code

### ISSUE THREAD

**Issue by smroush** [exaloop/codon#394]
I thought it would be interesting to compare codon timings to pypy3 for some fairly simply Python code.
I downloaded and installed Codon 0.16.  An attempt to run the program gave the following errors, which are inexplicable to me:

codon run EulerProblem299.py
EulerProblem299.py:46:17-34: error: 'float' does not match expected type 'int'
├─ EulerProblem299.py:57:15-54: error: during the realization of findOddValuesOfA(inLimit: int, inSaveTuples: bool)
╰─ EulerProblem299.py:65:73-95: error: during the realization of bruteForce(inLimit: int, inSaveTuples: bool)
[EulerProblem299.py.txt](https://github.com/exaloop/codon/files/11617016/EulerProblem299.py.txt)

Source code runs fine with Python and pypy3.  I am not aware of any code in the attached file which generates a float.
I have no idea why the "error: during the realization of" are occuring in; code seems pretty vanilla.

**Comment by elisbyberi** [comment]
@smroush This issue is now fixed #396

**Comment by inumanag** [comment]
Closing this as it should be fixed: please reopen if it still persists.
