### ISSUE TITLE
math.gcd() returns a float

### ISSUE THREAD

**Issue by elisbyberi** [exaloop/codon#395]
The Codon `math.gcd()` returns a float, whereas the Python `math.gcd()` returns an integer.

https://docs.python.org/3/library/math.html#math.gcd
_Return the greatest common divisor of the specified integer arguments. If any of the arguments is nonzero, then the returned value is the largest positive **integer** that is a divisor of all arguments. If all arguments are zero, then the returned value is 0. gcd() without arguments returns 0._

https://github.com/exaloop/codon/blob/1fcd2f296be3192a1c5c79e1f34fee00df1cdc63/stdlib/math.codon#L519

This issue occurs in #394

**Comment by arshajii** [comment]
Good catch... should be an easy fix.

**Comment by elisbyberi** [comment]
@arshajii While this simple `gcd()` implementation would suffice, [Lehmer's GCD algorithm](https://en.wikipedia.org/wiki/Lehmer%27s_GCD_algorithm) is preferred:
``` Python
def gcd(*integers: int):
    a = integers[0]
    for b in integers[1:]:
        while b:
            a, b = b, a % b

    return a


print(gcd(4, 6, 8, 10, 12, 0))  # 2
print(gcd(3, 6, 9, 12, 15, 0))  # 3

```

**Comment by arshajii** [comment]
Fixed in https://github.com/exaloop/codon/pull/396 (I just used the gcd/lcm algorithms from CPython).

**Comment by elisbyberi** [comment]
@arshajii GCD is now implemented [in C using Lehmer's GCD algorithm](https://github.com/python/cpython/blob/e6373c0d8b59512aa7f0dea7f3fb162b6ed10fa4/Objects/longobject.c#LL5380C67-L5380C67). While I don't have benchmarking results at the moment, it's worth noting that Lehmer's GCD algorithm is particularly efficient for long integers.

I may reopen this issue to explore alternative GCD algorithms and give them a try.
