### ISSUE TITLE
how to build an exe that can run machines without codon

### ISSUE THREAD

**Issue by ChenyueYuan2003** [exaloop/codon#397]
I built two exe by `codon build -release -exe nw.py` and `codon build -exe nw.codon` with codon. But when I run executables on another machine without codon. Neither of them can run, there will be same error.

**./nw: error while loading shared libraries: libcodonrt.so: cannot open shared object file: No such file or directory**

I know this is due to a lack of codon libraries at runtime. But I really want to know how to build or encapsulate an exe that can run on machines without codon.

Besides, I would like to know why there is a big difference in the running speed of these two executables. The first executable is one-fifth the size of the second, but nearly 20 times as fast.

**Comment by elisbyberi** [comment]
@ChenyueYuan2003 The use of shared libraries provides several benefits, including code reusability, **efficient memory utilization**, and ease of updating libraries without recompiling the entire program. Codon has multiple dependencies, leading to a significant increase in the executable file size. It will definitely exceed 1GB.

**Comment by ChenyueYuan2003** [comment]
Thank you for the explanation, it deepened my understanding of Codon.

**Comment by ChenyueYuan2003** [comment]
> @ChenyueYuan2003 The use of shared libraries provides several benefits, including code reusability, **efficient memory utilization**, and ease of updating libraries without recompiling the entire program. Codon has multiple dependencies, leading to a significant increase in the executable file size. It will definitely exceed 1GB.

Thank you for the explanation, it deepened my understanding of this

**Comment by arshajii** [comment]
FYI we are looking into a fully statically-linked option that avoids needing to link to the runtime library (`libcodonrt.so`); no ETA but it is on our roadmap (https://docs.exaloop.io/codon/general/roadmap#infrastructure-and-tools).

Aside from that, the `-release` flag performs optimizations like `-O3` on Clang/GCC, which is why the performance and binary size are different.

**Comment by ChenyueYuan2003** [comment]
> FYI we are looking into a fully statically-linked option that avoids needing to link to the runtime library (`libcodonrt.so`); no ETA but it is on our roadmap (https://docs.exaloop.io/codon/general/roadmap#infrastructure-and-tools).
> 
> Aside from that, the `-release` flag performs optimizations like `-O3` on Clang/GCC, which is why the performance and binary size are different.
Thanks for the explanation. Codon has been great so far and helped me complete my assignment brilliantly, looking forward to following up with further work.

**Comment by ChenyueYuan2003** [comment]
> FYI we are looking into a fully statically-linked option that avoids needing to link to the runtime library (`libcodonrt.so`); no ETA but it is on our roadmap (https://docs.exaloop.io/codon/general/roadmap#infrastructure-and-tools).
> 
> Aside from that, the `-release` flag performs optimizations like `-O3` on Clang/GCC, which is why the performance and binary size are different.

Thanks for the explanation. Codon has been great so far and helped me complete my assignment brilliantly, looking forward to following up with further work.
