### ISSUE TITLE
Division by zero returned inf

### ISSUE THREAD

**Issue by likecodingloveproblems** [exaloop/codon#404]
In python when an integer divided by zero, ZeroDivisionError returned but when the code is compiled by codon the result is inf.
to reproduce bug, you can run the below code.
```
def zero_division():
    print(1 / 0)
zero_division()
```

**Comment by elisbyberi** [comment]
Something divided by zero is undefined, `ZeroDivisionError` should be raised.
Something divided by 0 is infinity is the only case when we use limit.

**Comment by elisbyberi** [comment]
@likecodingloveproblems Duplicate of #173 See: https://docs.exaloop.io/codon/general/releases#semantics

**Comment by inumanag** [comment]
Also: https://docs.exaloop.io/codon/general/differences
