### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'nm'

### ISSUE THREAD

**Issue by rakshyak-98** [exaloop/codon#412]
this is the error log: [codon-installation.log](https://github.com/exaloop/codon/files/11905124/codon-installation.log)
I tried to install codon-jit using `pip install codon-jit`.
pip version: 23.1.2
python version: 3.7.16
I am using Docker image apache/airflow, inside that, Tried to install codon-jit.

**Comment by arshajii** [comment]
Hi @rakshyak-98 -- I don't think this is a problem on our end, but rather a general permissions issue when `pip install`ing (?). Do any of the solutions [here](https://stackoverflow.com/questions/31512422/pip-install-failing-with-oserror-errno-13-permission-denied-on-directory) work?
