### ISSUE TITLE
Cannot append entry to list of dictionaries

### ISSUE THREAD

**Issue by aresper** [exaloop/codon#416]
I have the following original python code (that works):

```
# initialize job graph vertices and create list of events
def initializeJobGraph(in_jobs, in_job_graph, in_events_dict):

    for each_job in in_jobs:

        # create vertex
        in_job_graph.addVertex(each_job, in_jobs[each_job]["budget"], in_jobs[each_job]["release"], in_jobs[each_job]["deadline"])

        # check if the release event already exists in the events list and add it
        if in_job_graph.vertList[each_job].getRelease() in in_events_dict.keys():
            in_events_dict[in_job_graph.vertList[each_job].getRelease()].append({'event': "release", 'job_id': in_job_graph.vertList[each_job].getId()})

        else:
            in_events_dict[in_job_graph.vertList[each_job].getRelease()] = [{'event': "release", 'job_id': in_job_graph.vertList[each_job].getId()}]

        # check if the deadline event already exists in the events list and add it
        if in_job_graph.vertList[each_job].getDeadline() in in_events_dict.keys():
            in_events_dict[in_job_graph.vertList[each_job].getDeadline()].append({'event': "deadline", 'job_id': in_job_graph.vertList[each_job].getId()})

        else:
            in_events_dict[in_job_graph.vertList[each_job].getDeadline()] = [{'event': "deadline", 'job_id': in_job_graph.vertList[each_job].getId()}]

    # build ordered event dict
    ordered_event_dict_tmp = collections.OrderedDict(sorted(in_events_dict.items(), key=lambda t: t[0]))

    return ordered_event_dict_tmp
```

I converted this code to the following to compile with Codon:

```
# initialize job graph vertices and create list of events
def initializeJobGraph(in_jobs, in_job_graph, in_events_dict: Dict[int, List[Dict[str, int]]]) -> Dict[int, List[Dict[str, int]]]:

    for each_job in in_jobs:

        # create vertex
        in_job_graph.addVertex(each_job, in_jobs[each_job]["budget"], in_jobs[each_job]["release"], in_jobs[each_job]["deadline"])

        # check if the release event already exists in the events list and add it
        if in_job_graph.vertList[each_job].getRelease() in list(in_events_dict.keys()):
            in_events_dict[in_job_graph.vertList[each_job].getRelease()].append({'event': "release", 'job_id': in_job_graph.vertList[each_job].getId()})

        else:
            in_events_dict[in_job_graph.vertList[each_job].getRelease()] = [{'event': "release", 'job_id': in_job_graph.vertList[each_job].getId()}]

        # check if the deadline event already exists in the events list and add it
        if in_job_graph.vertList[each_job].getDeadline() in list(in_events_dict.keys()):
            in_events_dict[in_job_graph.vertList[each_job].getDeadline()].append({'event': "deadline", 'job_id': in_job_graph.vertList[each_job].getId()})

        else:
            in_events_dict[in_job_graph.vertList[each_job].getDeadline()] = [{'event': "deadline", 'job_id': in_job_graph.vertList[each_job].getId()}]

    # build ordered event dict
    ordered_event_dict_tmp = collections.OrderedDict(sorted(in_events_dict.items(), key=lambda t: t[0]))

    return ordered_event_dict_tmp
```
But I am getting the following compilation error:

```
me@desktop:~/Python-sandbox/23-07-01-codon-typecheck-fix$ codon build -release -exe main_0_0.py 
main_0_0.py:200:13-153: error: 'List[Dict[str,int]]' object has no method 'append' with arguments (List[Dict[str,int]], Dict[str,pyobj])
├─ main_0_0.py:3073:26-74: error: during the realization of initializeJobGraph(in_jobs: pyobj, in_job_graph: pyobj, in_events_dict: Dict[int,List[Dict[str,int]]])
╰─ main_0_0.py:3087:5-9: error: during the realization of main(arg1: str, arg2: str)

```
Any ideas on what is causing the data types mismatch that is forbidding the 'append' operation?
Here is a example of an entry of the in_events_dict data structure :
{29556: [{'event': 'release', 'job_id': 1}], 59556: [{'event': 'deadline', 'job_id': 1}, {'event': 'release', 'job_id': 2}]}

**Comment by elisbyberi** [comment]
@aresper What is the code in line 200?
`main_0_0.py:200:13-153: error: 'List[Dict[str,int]]' object has no method 'append' with arguments (List[Dict[str,int]], Dict[str,pyobj])`

If you create an object of type `List[Dict[str, int]]`, you can only append objects of type `Dict[str, int]`.

**Comment by aresper** [comment]
Thanks @elisbyberi, here is a screenshot with the line numbers:
![image](https://github.com/exaloop/codon/assets/138171089/95add65a-fc49-4120-bfbd-7fce83e1b7b9)
I will check again the data types, but I am having a hard time to figure out the issue,

**Comment by kellantech** [comment]
It looks like on line 200, the dictionary you append contains `"event":"release"` as one of its key pairs, which is incompatible with Dict[str, int].

**Comment by aresper** [comment]
Now I see it, thanks!
I have updated the Dict type declaration as follows and now the code compiles:
Dict[int, List[Dict[str, Union[str, int]]]]

**Comment by aresper** [comment]
Hi, actually after performing the changes above I am getting a segmentation fault when compiling.
I tracked the error to the following declaration of the in_events_dict parameter above:

`events_dict: Dict[int, List[Dict[str, Union[str, int]]]] = field(default_factory=dict)`

Any ideas?

**Comment by elisbyberi** [comment]
@aresper What does `field(default_factory=dict)` return? Please try to isolate the problem and provide a minimal reproducible example. Based on the return type of `field(default_factory=dict)`, you can predefine the type for `events_dict`.

**Comment by aresper** [comment]
Sorry, it seems that was wrongly trying to initialize the events dict in the same way as inside a data class:

```
# Class to generate the Jobs graph
@dataclass
class JobGraph:
    vertList: Dict[str, JobVertex] = dataclasses.field(default_factory=dict)
    numVertices: int = 0
```
If I declare like this, the segmentation fault does not occur:
```
# initialize events dict
    events_dict: Dict[int, List[Dict[str, Union[str, int]]]] = {}
```
So, going back to the issue with line 200 that is still ocurring:
```
me@desktop:~/Python-sandbox/23-07-01-codon-typecheck-fix$ codon build -release -exe main_0_0.py
main_0_0.py:200:13-153: error: 'List[Dict[str,Union[int,str]]]' object has no method 'append' with arguments (List[Dict[str,Union[int,str]]], Dict[str,pyobj])
├─ main_0_0.py:3073:26-74: error: during the realization of initializeJobGraph(in_jobs: pyobj, in_job_graph: pyobj, in_events_dict: Dict[int,List[Dict[str,Union[int,str]]]])
╰─ main_0_0.py:3087:5-9: error: during the realization of main(arg1: str, arg2: str)
```
It seems to me that Codon thinks the return type of:
`in_job_graph.vertList[each_job].getId()`
is an object (pyobj), but this method of the class actually returns an integer.

I will paste here the declarations of the involved classes:

```
import python
from python import dataclasses, dataclass, field
from typing import Dict

# Importing JobVertex and IntervalVertex classes from their respective modules
from python import vertex_0_0.JobVertex
from python import vertex_0_0.IntervalVertex

# Class to generate the Jobs graph
@dataclass
class JobGraph:
    vertList: Dict[str, JobVertex] = dataclasses.field(default_factory=dict)
    numVertices: int = 0

    def addVertex(self, key, budget, release, deadline):
        self.numVertices += 1
        newVertex = JobVertex(key, budget, release, deadline)
        self.vertList[key] = newVertex
        return newVertex

    def getVertex(self, n):
        return self.vertList.get(n)
```

```
from python import dataclasses, dataclass
from typing import List

class JobVertex:
    id: int
    budget: int
    release: int
    deadline: int
    parent: List[Tuple[int, int]]
    child: List[Tuple[int, int]]
    active: bool
    isLeaf: bool
    intervals: List[Tuple[int, int]]
    intervals_assigned: bool
    start_time: int
    core: int

    # getters
    def getId(self):
        return self.id
```
Any help will be appreciated, I will continue investigating.
Note: the functions in the classes are still missing the input and return data types - still working on that, but I don't think that is causing the issue above.

**Comment by aresper** [comment]
Hi, I think I have isolated the issue (or at least part of it), which is reproducible by the following code:

```
from typing import Dict, List, Union
d: Dict[str, Union[str, int]]
d = {'key1': "hi"}
d['key2'] = 3
```
```
me@desktop:~/Python-sandbox/23-07-01-codon-typecheck-fix$ codon build -release -exe dict-test.py
dict-test.py:4:1-14: error: 'Dict[str,str]' object has no method '__setitem__' with arguments (Dict[str,str], str, int)
```
So there are two possible explanations:
1. The importing of Union type is not been done correctly (to be honest I still confuse when I have to import from python or from Codon)
2. Codon definitely does not support dicts with key pairs of different data types, even using the Union type

BTW, the importing of Union type in my original code was missing. So adding it had not effect.

Any ideas?

**Comment by elisbyberi** [comment]
@aresper Try this:
```Python
from typing import Dict, List, Union

d = Dict[str, Union[str, int]]()  # d: Dict[str, Union[str, int]] = {}

d['integer'] = 3
d['string'] = '4'

print(d)  # {'integer': 3, 'string': '4'}
print(type(d['string']) is Union[str, int])  # True

```

**Comment by aresper** [comment]
Cool, this works, thanks. I will try to integrate this solution in the rest of the code.
Any ideas if it is possible to initialize both key pairs at the same time?
d = {'integer': 3, 'string': '4'} does not work...

**Comment by elisbyberi** [comment]
@aresper Please remember that the values in the dictionary are of type Union.
```Python
# i: Union[int, str] = 1
# s: Union[int, str] = '3'
# d: Dict[str, Union[str, int]] = {
#     'integer': i,
#     'string': s
# }

d: Dict[str, Union[str, int]] = {
    'integer': Union[int, str](1),
    'string': Union[int, str]('3')
}

print(d)  # {'integer': 1, 'string': '3'}
```

**Comment by inumanag** [comment]
You are having a `pyobj`---an object from Python---lurking somewhere (either from `from python import` or from `@python` function). Codon automatically translates pyobjs to/from the native types; however, the translation is shallow and does not handle "deep" references (in other words, no depth subtyping). For example, if you have `def foo(x: int)`, calling `foo(pyobj)` will cast pyobj to `int`; however, `foo([pyobj])` won't work with `def foo(x: list[int])`.

**Comment by inumanag** [comment]
> Cool, this works, thanks. I will try to integrate this solution in the rest of the code.
> Any ideas if it is possible to initialize both key pairs at the same time?
> d = {'integer': 3, 'string': '4'} does not work...

Not yet possible; we are working on this one.

**Comment by aresper** [comment]
Hi, thanks for the useful comment and insights.
The issues previously reported were isolated and solved as follows:

- Issue 1: using in_job_graph.vertList[each_job].getRelease() as a key for in_events_dict was the object causing the "deep" referencing issue explained. This issue was solved by simply indicated that to the compiler that this value is in fact a simple integer, i.e., using int(in_job_graph.vertList[each_job].getRelease()) solved the problem;
- Issue 2: the appending operation with the key pair {'event': "release", 'job_id': in_job_graph.vertList[each_job].getId()} had to be updated with the correct types as follows: {'event': Union[int, str]("release"), 'job_id': Union[int, str](job_id)}
Note: curiously the compiler does not seem to be complaining that I am adding the two key pairs at the time in the append operation.

Here is what the functions looks like now, after the changes above:
![image](https://github.com/exaloop/codon/assets/138171089/2003f32a-2f39-4a58-a7f4-93f38624795a)

I am now having a segmentation fault in the last line (225) of the function initializeJobGraph() reported above:
```
    # build ordered event dict
    ordered_event_dict_tmp = collections.OrderedDict(sorted(in_events_dict.items(), key=lambda t: t[0]))
```
But this is is another fight. Probably should be raised in a different ticket, if necessary.
Final question: is there a method to debug the segmentation fault error, to know exactly which line is causing it?.

**Comment by inumanag** [comment]
Union type support is still a work in progress: that might be the reason.

You can compile an executable in debug mode (`codon build foo.codon -o foo.exe`) and then run `foo.exe` via LLDB. That should give you the location of the segfault. I can also take a look if you happen to have a small example to reproduce the issue.

**Comment by aresper** [comment]
Thanks, will try that.
I opened a new issue with a sample reporduceable code for the segmentation fault issue:
https://github.com/exaloop/codon/issues/423
