### ISSUE TITLE
Codon does not import  external modules such as numpy and matplotlib

### ISSUE THREAD

**Issue by iajzenszmi** [exaloop/codon#417]
Codon does not import  external modules such as numpy and matplotlib

**Comment by elisbyberi** [comment]
@iajzenszmi Codon can import only Codon modules, and pure-Python modules (modules that only contains Python code, and doesn't include C extensions or code in other languages). Both numpy and matplotlib make use of C extensions.

You can make use of CPython to import these modules. See https://docs.exaloop.io/codon/interoperability/python

**Comment by inumanag** [comment]
For many Python libraries, you need to use `from python import XYZ` at the moment.
