### ISSUE TITLE
I cannot use input()

### ISSUE THREAD

**Issue by j-f-paris** [exaloop/codon#419]
Odeon:~/Documents/Courses/1306/Python$ more codonTest.py
""" Test codon compatibility """
name = ""
name = input("What's your name? ")
print("So, your name is", name)
Odeon:~/Documents/Courses/1306/Python$ python3 codonTest.py
What's your name? Bill
So, your name is Bill
Odeon:~/Documents/Courses/1306/Python$ codon run codonTest.py
codonTest.py:3:8-13: error: name 'input' is not defined
jfparis@Odeon:~/Documents/Courses/1306/Python$

**Comment by elisbyberi** [comment]
Duplicate of #96

**Comment by inumanag** [comment]
Thank you, @elisbyberi.
