### ISSUE TITLE
can't use in sub-system wsl in win10

### ISSUE THREAD

**Issue by Aeymeng** [exaloop/codon#421]
i try to run codon run fib.py

fib.py code is as follows：from python import numpy as np

but raise error:
Raised from: std.internal.dlopen.dlopen.2:0

Aborted(core dumped)

**Comment by inumanag** [comment]
I guess Codon cannot locate Python library: you will need to set up `CODON_PYTHON` to point to a proper Python library. See https://docs.exaloop.io/codon/interoperability/python. You might need to  install Python in WSL as well.
