### ISSUE TITLE
Builtin `min()` does not support argument `key`

### ISSUE THREAD

**Issue by akleemans** [exaloop/codon#422]
I have the following code:

```python
distances = {'a': 4, 'b': 1}
queue = ['a', 'b']
u = min(queue, key=distances.get)
queue.remove(u)
print(queue)
```

When run with Python 3.11.1, I get the expected result printed:
```
> python3 min_example.py
['a']
```

If I try to run it with Codon 0.16.2, I get the following:

```bash
> codon run min_example.py 
min_example.py:3:20-33: error: 'key' is an invalid keyword argument for min()
```

Is this expected? I assumed the `key` parameter would be supported for `min()`.

**Comment by arshajii** [comment]
Thanks for the report -- yes we definitely should support that. We'll plan to have it in the next release!

**Comment by akleemans** [comment]
Awesome, thanks very much!

**Comment by akleemans** [comment]
By the way, this is also the case for `max()`.
For example, for finding the most common letter in `letters`, this is a short way of writing it:
`most_common = max(set(letters), key=letters.count)`

Unfortunately this still throws an error in Codon 0.16.3:
`error: 'key' is an invalid keyword argument for max()`

**Comment by arshajii** [comment]
Hi @akleemans, I've created a PR for this here: https://github.com/exaloop/codon/pull/505 -- it'll be included in the next version that we plan to release in the next couple weeks!

**Comment by akleemans** [comment]
Awesome, appreciate it!

**Comment by avitkauskas** [comment]
I see PR #505 was merged and this issue can be closed now.

**Comment by akleemans** [comment]
As @avitkauskas pointed out, this has been merged, closing.
