### ISSUE TITLE
Linux system installation issues

### ISSUE THREAD

**Issue by muyi151** [exaloop/codon#426]
Hello! I would like to install Codon on a Linux system, but due to network restrictions, I am unable to download and install the "install.sh" file. Even if I manually download the "install.sh" file and try to install it using the command "bash install.sh", it fails due to network issues. Is it possible for you to provide an offline version of the installation package? It would be great if you could integrate all the necessary files into a single sh file for direct installation. Thank you!

**Comment by inumanag** [comment]
Please check https://github.com/exaloop/codon/releases/tag/v0.16.2: all releases are there. It is sufficient to extract them into `$HOME/.codon` (or any other path, for that matter) and run `$HOME/.codon/bin/codon`.
