### ISSUE TITLE
from threading import Thread gives Error

### ISSUE THREAD

**Issue by FatemehAhsan** [exaloop/codon#430]
Hi.
I tried to use codon for this [code](https://github.com/vasugupta9/DeepLearningProjects/blob/main/MultiThreadedVideoProcessing/video_processing_parallel.py)  (This is a simple code for faster video processing using Multi-Threading in Python) but it raised the below error:

video_processing_parallel.py:4:23-29: error: cannot import name 'Thread' from 'threading'

![Screenshot from 2023-07-24 17-07-46](https://github.com/exaloop/codon/assets/100623985/c3b06ed9-96b3-4ab3-9611-b42b26cea59d)

Using:
  Ubuntu 22.04 LTS
  Python 3.10.6

Thanks.

**Comment by inumanag** [comment]
Unfortunately class `Thread` is not yet implemented in Codon. You can use `@par` for now; this should be fixed in subsequent releases.

**Comment by inumanag** [comment]
Merging into #608 .
