### ISSUE TITLE
How to compile python code that uses PyQt5?

### ISSUE THREAD

**Issue by arnoldjames98** [exaloop/codon#436]
I have code with imports like:
```python
from PyQt5 import QtWidgets, QtCore, uic
from PyQt5.QtWidgets import *
```

But am not sure how to change this so I can compile with Codon. For all other imports I just prepend "from python" but of course this doesn't work.

**Comment by rwaelder** [comment]
Bumping this, I have the same question/issue.

**Comment by Jeck-Liu-Create** [comment]
I have the same question/issue.

**Comment by qlz-scut** [comment]
I have the same question/issue.

**Comment by inumanag** [comment]
You will have to do `from python import Qt5` or `from python import PyQt5.QtWidgets`. However, Codon will not be able to compile this and you will not gain any Codon speedups.
