### ISSUE TITLE
Error: cannot find -lz: No such file or directory

### ISSUE THREAD

**Issue by DeathBeastLLC** [exaloop/codon#441]
I have this error when i try to build into an executable but running the python file is fine and doesn't throw any errors.

- System: Ubuntu 22.04 LTS On Windows WSL
- Command: `codon build -exe main.py`
- Output:
```
/usr/bin/ld: cannot find -lz: No such file or directory
collect2: error: ld returned 1 exit status
error: process for 'g++' exited with status 1
```
- main.py:
`print("Hello world")`

Codon seems to successfully build on object file, but can't link it into an executable.

**Comment by arshajii** [comment]
Hi @DeathBeastLLC, this is because you don't have `zlib` installed -- you can install it with `sudo apt-get install zlib1g-dev`. Let me know if the issue persists after that.

**Comment by DeathBeastLLC** [comment]
Hi @arshajii Thank you for helping me! Everything now works.
