### ISSUE TITLE
OpenMP's ordered construct or decorator not working

### ISSUE THREAD

**Issue by marioroy** [exaloop/codon#442]
I tried the ordered decorator without success. So, I changed it to critical for my [t_is_prime](https://gist.github.com/marioroy/6944e9196a8eff562ac38fe01d85f465) demonstration.
```python
@omp.critical
def show_chunk_info(chunk_id):
    print(f"{chunk_id}", flush=True)
```

Testing with `@omp.ordered` has no output other than the number of chunks (1st line in the output). 
```python
import openmp as omp
from sys import argv, exit, stdout
from math import floor, sqrt

def divide_up(dividend, divisor):
    if dividend % divisor:
        return int(dividend // divisor) + 1
    else:
        return int(dividend // divisor)

@omp.ordered
def show_chunk_info(chunk_id):
    print(f"{chunk_id}", flush=True)

def is_prime(n):
    q = int(floor(sqrt(n)))
    chunk_size = 510510  
    num_chunks = divide_up(q, chunk_size)
    print(f"num_chunks => {num_chunks}")

    @par('schedule(dynamic,1) ordered num_threads(8)')
    for chunk_id in range(num_chunks):
        show_chunk_info(chunk_id)

    return True

if __name__ == "__main__":
    candidate = int(argv[1]) if len(argv) > 1 else 67280421310721
    is_prime(candidate)
```

Correct behavior: orderly output. 
```text
$ codon run test.codon
num_chunks => 17
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
```

**Comment by arshajii** [comment]
Thanks for the report, @marioroy -- I've fixed this in https://github.com/exaloop/codon/pull/440/commits/bbbfae002ddfada49e4c36e65be8b04e570af8c9, which will be in the next release!

**Comment by marioroy** [comment]
Thank you, @arshajii -- Branch `bugfixes-2023-08` is working.

**Comment by marioroy** [comment]
@arshajii -- I changed the parallel block in [t_is_prime.py](https://gist.github.com/marioroy/6944e9196a8eff562ac38fe01d85f465#file-t_is_prime-codon).  I wished that OpenMP had omp.for_break and omp.for_continue capabilities and not resort to exiting the application early. This is the thing that I miss using OpenMP, and now Codon.

```python
    @par(schedule='dynamic', chunk_size=1, ordered=True)
    for chunk_id in range(num_chunks):
        low = uint(chunk_size) * uint(chunk_id) + uint(6) - uint(1)
        high = low + uint(chunk_size) - uint(1)
        if high > q: high = q

        if _DEBUG:
            show_chunk_info(chunk_id, low, high)

        while True:
            if low > high:
                break
            if n % low == uint(0) or n % (low + uint(2)) == uint(0):
                not_prime += 1
                break
            low += uint(6)

        if not_prime:
            # OpenMP lacks omp.for_break/omp.for_continue capabilities.
            terminate_early(n)  # exit the application
```

**Comment by marioroy** [comment]
Re-opening this issue. The `@openmp.ordered` decorator is not working 100%. For example, if having more threads than the number of chunks, the application hangs during orderly output. I will report back with a new gist containing C and Codon parallel segmented sieve demonstrations.

**Comment by marioroy** [comment]
Ah, I was in the wrong folder. Orderly is working.
