### ISSUE TITLE
OpenMP: Unable to specify a shared variable

### ISSUE THREAD

**Issue by marioroy** [exaloop/codon#448]
From the documentation, _"Other OpenMP parameters like private, shared or reduction, are inferred automatically by the compiler."_

What if Codon assumes wrongly? I wish for the ability to specify `last_completed` a shared variable, not made private. I'm in a critical block and not incrementing the variable, but instead assigning a value (e.g. not for reduction).

```python
last_completed = -1

@omp.critical
def show_progress(high, limit):
    completed = int(float(high) / limit * 100)
    if completed != last_completed:
        last_completed = completed
        print(f"\rprogress {completed}% ", file=stderr, flush=True, end='')
        stderr.flush()
```

**Error:**

```text
error: local variable 'last_completed' referenced before assignment
```

It's has been an interesting journey, experimenting with OpenMP using C and Codon.

**Comment by elisbyberi** [comment]
@marioroy `last_completed` is a **global** vaiable. You are referencing it in `if completed != last_completed:` before assignment. The assignment happens at `last_completed = completed`. At this point `last_completed` is no longer a **global** variable. This doesn't work in Python either.

**Comment by marioroy** [comment]
Thank you, @elisbyberi. I see now and understand.
