### ISSUE TITLE
sqrt of Int and UInt types

### ISSUE THREAD

**Issue by zoeleu** [exaloop/codon#459]
How would I calculate the sqrt of Int and UInt numbers?

**Comment by arshajii** [comment]
Something like this?

``` python
import math
x = UInt[128](144)
print(math.sqrt(float(x)))  # 12
```

**Comment by matteoturini** [comment]
> index.py:6:14-30: error: no function 'sqrt' with arguments (UInt[81])

**Comment by matteoturini** [comment]
@arshajii Is there no way?

**Comment by arshajii** [comment]
@matteoturini are you sure you're using the right code? In my snippet, `sqrt` is called on a `float` not a `UInt`.

**Comment by matteoturini** [comment]
I can't convert it to a float, my number would overflow.

**Comment by inumanag** [comment]
Right now `sqrt` only works on floats (which are 64-bit floats in codon). We do not have support for large (U)Ints as of this time. 

Merging it with #235.
