### ISSUE TITLE
"expected type expression" for third-party base class in inheritance

### ISSUE THREAD

**Issue by sdflkjssl** [exaloop/codon#463]
When I tried to run this:

```python
from python import torch.nn as nn

class Network(nn.Module):
    ...
```

Gives me the error: "expected type expression" on `nn.Module` (or other third-party classes such as `numpy.ndarray`) during building, while `nn.Module()` can be called directly to initialize a module instance. Also, it doesn't give me an error when the base class is defined by myself.

**Comment by inumanag** [comment]
Sorry, we do not yet support overloading Python classes (`from python...`), and I am not sure if we will ever get to that. I'd suggest refactoring the code for now (maybe storing the `nn.module` as the object member).
