### ISSUE TITLE
Integer overflow error when calculating large Fibonacci numbers

### ISSUE THREAD

**Issue by MohammadMMoniri** [exaloop/codon#467]
When testing the fib function defined in the Example section with a very large input like 10000000000000000000000000000000000000000000000000000000000000, I encountered an integer overflow error:

`fib.py:7:5-67: error: integer '10000000000000000000000000000000000000000000000000000000000000' cannot fit into 64-bit integer
`
However, when running the same code using the CPython interpreter, it executes without errors.
Is there any solution for using large inputs?

**Comment by marioroy** [comment]
One may need to specify a string or UInt[N] may fail e.g. `UInt[N]("1000000000...big_integer")`.  

```python
import sys

bigint = UInt[1024]

def strToBigInt(what: str) -> bigint:
    # Convert a string to big Int, supporting scientific notation.
    try:
        n = bigint(what)
    except:
        try:
            s = f"{float(what):.1f}"
        except:
            print("Invalid integer.", file=sys.stderr)
            sys.exit(1)
        p = s.rfind('.')
        n = bigint(s[:p])
    return n

def fib(n: bigint):
    a, b = bigint(0), bigint(1)
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
    print()

fib(bigint("10000000000000000000000000000000000000000000000000000000000000"))
fib(strToBigInt("1e61"))
fib(strToBigInt("1.0000001e58"))
```

**Comment by marioroy** [comment]
Try to specify a string if `UInt[N](1000...big_integer)` fails e.g. `UInt[N]("1000...big_integer")`.  That works.

```python
bigint = UInt[1024]

def fib(n: bigint):
    a, b = bigint(0), bigint(1)
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
    print()

fib(bigint("10000000000000000000000000000000000000000000000000000000000000"))
```

**Comment by arshajii** [comment]
This is indeed because of Codon's 64-bit `int` -- the workaround with `UInt[256]` is above and we'll likely look into adding a arbitrary-width `long` type at some point as well.
