### ISSUE TITLE
Trouble with install.sh; uname -m on ubuntu

### ISSUE THREAD

**Issue by matthew-parrott** [exaloop/codon#479]
When I run install.sh on ubuntu 22.04, I get this error (note, this is within a docker build using ubuntu:22.04 as the base):

```
#7 [ 3/12] RUN /bin/bash -c "$(curl -fsSL https://exaloop.io/install.sh)"
#7 0.253   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#7 0.253                                  Dload  Upload   Total   Spent    Left  Speed
   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 100     9  100     9    0     0     34      0 --:--:-- --:--:-- --:--:--    34
 #7 0.525
 #7 0.525 gzip: stdin: not in gzip format
```

From within the container, I see that `uname -m` returns `aarch64`. `install.sh` uses `CODON_BUILD_ARCHIVE=codon-$OS-$ARCH.tar.gz` to find the tar to download. But, there's no `aarch64` build available here: https://github.com/exaloop/codon/releases/tag/v0.16.3

Any advice? Thanks!

**Comment by matthew-parrott** [comment]
Ah, never mind. It turns out that because I'm working on a Mac M1, I needed to turn on linux emulation in my Dockerfile:
`FROM --platform=linux/amd64 ubuntu:22.04`

Then, when I run `uname -m`, I get `x86_64` and codon installs just fine.

**Comment by inumanag** [comment]
Thank you for the solution! :)
