### ISSUE TITLE
How to use dataclasses in Codon

### ISSUE THREAD

**Issue by matthew-parrott** [exaloop/codon#481]
Hi there -- could you provide some examples of how to use dataclasses in Codon? I checked the documentation, but didn't find any. My apologies if I missed them.

It's not clear to me if I should do `from dataclasses import dataclass`, not use a decorator, or use the `@dataclass` decorator even though it's not explicitly imported.

**Comment by inumanag** [comment]
Hi @matthew-parrott 

Just use `@dataclass` without the import. Note that all classes in Codon are Python dataclasses. Some dynamic features, however, are not yet supported.
