### ISSUE TITLE
frozen sets

### ISSUE THREAD

**Issue by ypfmde** [exaloop/codon#494]
The data type `frozenset` seems to be missing in codon. Is there a good substitute?

-- Peter Mueller

**Comment by arshajii** [comment]
Hi @ypfmde -- is it possible to just use regular sets for your use case (until we add `frozenset` to the standard library)?

**Comment by ypfmde** [comment]
I'm using sets of frozen sets of integers. I tried to replace the frozen sets by tuples.  But this fails due to missing hash values for the data type Array[int], if I understand the messages right.

**Comment by inumanag** [comment]
@ypfmde Use `List` instead of `Array` and it should work; `Array` is internal type and is not meant to be used in user code.

**Comment by inumanag** [comment]
Merging into #608 .
