### ISSUE TITLE
[Question]: the BSL license applies to my program for production itself?

### ISSUE THREAD

**Issue by nacho00112** [exaloop/codon#495]
Let's suppose i have two programs for production, in the first i used codon to compile it but didn't include the codon compiler inside, in the second i still used codon to develop it but this time i included codon within the program, in which ones the BSL license applies?

I need to know this cuz i want to develop libraries using codon, just like cython, and post them in github, without including codon within the library.

Resuming i want to know if the license basically prohibits including codon compiler in programs for production without adquiring a more permissive license or it applies even though it doesn't include the compiler inside but was compiled with it or the license doesn't apply as long as it doesn't include codon inside.

**Comment by arshajii** [comment]
Sorry for the delay on this -- the license applies to using Codon itself (i.e. the compiler when compiling, or the runtime when running programs). So you can develop Codon libraries under any license, but the end user who is using Codon and the library would be doing so under Codon's BSL license. Happy to expand on this or clarify anything further.

**Comment by inumanag** [comment]
See #203 for future plans.
