### ISSUE TITLE
random.codon:263:13-16: error: name 'INF' is not defined

### ISSUE THREAD

**Issue by tuneman7** [exaloop/codon#497]
This seems like a great project, I'm unsure why I'm getting this error.

environment Ubutu Docker image.

Here is my Command

codon run gen_random_data.py 

---   Here is the error I receive

gen_random_data.py:1:8-11: error: no module named 'csv'
random.codon:263:13-16: error: name 'INF' is not defined
random.codon:661:24-31: error: name '_bisect' is not defined

Below is the code:

import csv
import os
import random
import string
from datetime import datetime, timedelta

def random_string(length=10):
    """Generate a random string of fixed length."""
    return ''.join(random.choice(string.ascii_lowercase) for _ in range(length))

def random_date(start, end):
    """Generate a random datetime between `start` and `end`."""
    return start + timedelta(
        seconds=random.randint(0, int((end - start).total_seconds())),
    )

def generate_csv(filename, size_limit=1024**3):
    """Generate a CSV file with a target size limit."""
    with open(filename, 'w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(['id', 'name', 'timestamp', 'value'])

        total_size = 0
        id_counter = 1
        start_date = datetime(2020, 1, 1)
        end_date = datetime(2023, 1, 1)

        while total_size < size_limit:
            row = [
                id_counter,
                random_string(10),
                random_date(start_date, end_date).strftime('%Y-%m-%d %H:%M:%S'),
                random.uniform(0, 1000)
            ]
            writer.writerow(row)
            id_counter += 1
            total_size = file.tell()

generate_csv('sample_data_to_transform.csv')

**Comment by arshajii** [comment]
Hi @tuneman7 -- Codon doesn't support the CSV module natively yet, but you can replace that with writing to the file directly:

``` python
import os
import random
import string
from datetime import datetime, timedelta

def random_string(length=10):
    """Generate a random string of fixed length."""
    return ''.join(random.choice(string.ascii_lowercase) for _ in range(length))

def random_date(start, end):
    """Generate a random datetime between start and end."""
    return start + timedelta(
        seconds=random.randint(0, int((end - start).total_seconds())),
    )

def generate_csv(filename, size_limit=1024**3):
    """Generate a CSV file with a target size limit."""

    def write_row(f, row):
        for i in range(len(row)):
            f.write(row[i])
            if i < len(row) - 1:
                f.write(', ')
        f.write('\n')

    with open(filename, 'w') as file:
        write_row(file, ('id', 'name', 'timestamp', 'value'))
        total_size = 0
        id_counter = 1
        start_date = datetime(2020, 1, 1)
        end_date = datetime(2023, 1, 1)

        while total_size < size_limit:
            row = (
                str(id_counter),
                random_string(10),
                str(random_date(start_date, end_date)),  # don't support strftime yet, but str() gives same format
                str(random.uniform(0, 1000))
            )
            write_row(file, row)
            id_counter += 1
            total_size = file.tell()

generate_csv('sample_data_to_transform.csv', size_limit=1000)
```

**Comment by inumanag** [comment]
Merging into #608 .
