### ISSUE TITLE
`from typing import Self` not supported

### ISSUE THREAD

**Issue by akleemans** [exaloop/codon#507]
When self-referencing inside a class, it is possible in Python to do 
```python
from typing import Self

class Node:
    neighbor: Self
```

Currently, referencing the `Node`-class directly is different in Python (`neighbor: 'Node'`) and Codon (`neighbor: Node`) so I thought it would be nice to use `Self`, so the script could run on both Python and Codon.

Could the `typing`-mock be extended with `Self`?

**Comment by inumanag** [comment]
Oh, we should add this—thanks for the suggestion! Right now you need to use `neighbor: Node`.

**Comment by inumanag** [comment]
Merging into #608 .
