### ISSUE TITLE
TypeVar and ParamSpec type expression fail

### ISSUE THREAD

**Issue by itssoap** [exaloop/codon#545]
Hi, I am trying to write a simple decorator to aid in Factorial calculation:

````python
from python import typing

cache_dict: dict = {}
T: typing.Type[typing.TypeVar] = typing.TypeVar('T')
P: typing.Type[typing.ParamSpec] = typing.ParamSpec('P')

def cache(func: typing.Callable[P, T]) -> typing.Callable[P, T]:
    global cache_dict
    def wrapper(*args: P.args, **kwargs: P.kwargs) -> typing.Type[T]:
        n = args[0]
        if str(n) not in cache_dict:
            temp = func(n)
            cache_dict[str(n)] = temp

        return cache_dict[str(n)]

    return wrapper



@cache
def fact(n: int) -> int:
    if n in (0, 1):
        return 1

    return n * fact(n-1)


def main() -> None:
    print(fact(15))

if __name__ == '__main__':
    main()
````

I have tried my best to type-hint wherever needed for the parameters and return types. I execute the code with
````bash
codon run test.py
````
But it fails with the following errors:
```
test.py:4:4-31: error: expected type expression
test.py:5:4-33: error: expected type expression
test.py:7:33-34: error: name 'P' is not defined
```

I have had success with running and even building the binary when the code only had the `fact()` function without the decorator function.

Please let me know if you need any further info to understand or replicate this scenario. Thanks

**Comment by elisbyberi** [comment]
@itssoap What you are attempting to do with [from python import](https://docs.exaloop.io/codon/interoperability/python#from-python-import) is not documented anywhere.

**Comment by itssoap** [comment]
@elisbyberi my attempt was inspired by the numpy example available in the same link that you have provided. When you say its not documented, do you refer to my usage of the typing module specifically or am I doing something incorrectly. Thanks

https://docs.exaloop.io/codon/interoperability/python#from-python-import:~:text=from%20python%20import%20numpy%20as%20np

**Comment by itssoap** [comment]
I was able to get it to run by switching to Decorator mode

````python
@python
def run():
    cache_dict: dict = {}
    
    def cache(func):
        def wrapper(*args, **kwargs) -> int:
            n = args[0]
            if str(n) not in cache_dict:
                temp = func(n)
                cache_dict[str(n)] = temp

            return cache_dict[str(n)]

        return wrapper
    
    @cache
    def fact(n: int) -> int:
        if n in (0, 1):
            return 1

        return n * fact(n-1)

    def main() -> None:
        print(fact(15))

    main()


if __name__ == '__main__':
    run()
````

Also, I could further use the same strongly typed code in this decorator, get the build generated and functioning:
````python
@python
def run():
    import typing
    cache_dict: dict = {}
    T = typing.TypeVar('T')
    P = typing.ParamSpec('P')

    def cache(func: typing.Callable[P, T]) -> typing.Callable[P, T]:
        def wrapper(*args: P.args, **kwargs: P.kwargs) -> typing.Type[T]:
            n = args[0]
            if str(n) not in cache_dict:
                temp = func(n)
                cache_dict[str(n)] = temp

            return cache_dict[str(n)]

        return wrapper

    @cache
    def fact(n: int) -> int:
        if n in (0, 1):
            return 1

        return n * fact(n-1)

    def main() -> None:
        print(fact(15))

    main()


if __name__ == '__main__':
    run()
````

But I am still interested in knowing how to make my original code (Interoperability mode) work, without shoving my whole code in the python decorator. Thanks

**Comment by elisbyberi** [comment]
@itssoap I am referring to your usage of the Python Typing module. Everything imported `from python` is just a Python object (PyObject). Hence, the `test.py:4:4-31: error: expected type expression` error. Use Codon objects for typing.

You will get the same error if you use the NumPy Python object for typing in Codon:
```Python
from python import numpy as np

x: np.array = np.array([1, 2, 3, 4]) * 10
print(x)  # [10 20 30 40]
```
```
i545.py:3:4-12: error: expected type expression
i545.py:4:7-8: error: name 'x' is not defined
```

**Comment by itssoap** [comment]
@elisbyberi Thanks for your hint! I made it work in Interoperability mode with types provided by codon:

````python
cache_dict = Dict[str, u64]()

def cache(func):
    global cache_dict
    def wrapper(n: u64) -> u64:
        if str(n) not in cache_dict:
            temp = func(n)
            cache_dict[str(n)] = temp

        return u64(cache_dict[str(n)])

    return wrapper



@cache
def fact(n: u64) -> u64:
    if n == u64(0) | n == u64(1):
        return u64(1)
    return n.__mul__(u64(fact(n-u64(1))))


def main():
    print(fact(u64(15)))

if __name__ == '__main__':
    main()
````

I guess it doesn't need the type of callable being returned as well, which was my main focus earlier.

Another interesting note is the time taken by Interoperability with Codon provided types vs `@python` Decorator, interoperability being a faster run:

![image](https://github.com/exaloop/codon/assets/6275744/92a22855-bd0c-4282-98f4-e050c7163fa7)

Though it would still be interesting to have support for Python classes as type-hints. Thanks
