### ISSUE TITLE
Interop with Python breaks CTRL+C

### ISSUE THREAD

**Issue by Tenchi2xh** [exaloop/codon#555]
Running the following code in Codon and interrupting it with <kbd>CTRL + C</kbd> works as expected:

```py
import time

print("ready")
while True:
    time.sleep(0.1)
```

```bash
$ codon run test.py
ready
^C
$
```

However, adding _any_ type of Python interop will disable breaking and will need killing the process to end it:

```py
import time
from python import PIL

print("ready")
while True:
    time.sleep(0.1)
```

```bash
$ codon run test.py
ready
^C^C^C^C^C^C^C^CKilled: 9
$
```

Also works with a `@python` decorator:

```py
import time

@python
def foo():
    pass

print("ready")
while True:
    time.sleep(0.1)
```

```bash
$ codon run test.py
ready
^C^C^C^C^C^C^C^CKilled: 9
$
```

**Comment by arshajii** [comment]
Thanks for the report -- I'm able to reproduce the issue. Going to investigate further... I wonder if libpython is somehow catching the interrupt signal and causing the issue.

**Comment by arshajii** [comment]
This is fixed in https://github.com/exaloop/codon/commit/36167bfab834756196491d6469221ff3020ef4de -- it'll be in the next release which will come out soon!
