### ISSUE TITLE
'codon run' a file which does not exist

### ISSUE THREAD

**Issue by douyixuan** [exaloop/codon#570]
The file 'a.codon' does not exist.
```
➜  codon git:(develop) ✗ codon run a.codon
[1]    27244 bus error  codon run a.codon
```

**Comment by arshajii** [comment]
Can you please share the OS you're on? In my case this gives an error message `error: cannot open file 'a.codon' for parsing` as expected.

**Comment by douyixuan** [comment]
```
$ uname
Darwin
$ sw_vers
ProductName:		macOS
ProductVersion:		14.4.1
BuildVersion:		23E224
$ arch
arm64
```

**Comment by inumanag** [comment]
Can you try the latest release? There we have fixes for macOS Sonoma and later versions (older releases had this issue, sadly)?
