### ISSUE TITLE
cannot import name “path” from “os.__init__”

### ISSUE THREAD

**Issue by PartehDev** [exaloop/codon#572]
I was making a shorthand for the Codon compiler with codon itself and ran into an issue when trying to compile, which it only threw when I tried to use “os.path.isfile” to check if a file existed. I don’t know why it happens, other than maybe the function doesn’t exist in Codon.

**Comment by arshajii** [comment]
Hi @PartehDev -- some functionality from the `os` module doesn't exist yet in Codon, but you can import `os` from Python and use it as normal:

``` python
from python import os  # use Python's 'os' module
import sys
print(os.path.isfile(sys.argv[1]))
```

**Comment by inumanag** [comment]
Merging into #608 .
