### ISSUE TITLE
Simple dynamic library in Codon that executes an external callback function every 1 second

### ISSUE THREAD

**Issue by gusaaaaa** [exaloop/codon#578]
We need to create a dynamic library in C or C++ that executes a callback every 1 second. The callback should be defined within the scope of the program that imports the library. We are investigating the possibility of doing it with Codon.

I am trying to at least have a first version that works, but I am at a point where I don't even know if this is possible with Codon and if it were possible, how to tackle the problem. Can some good Samaritan give me a hand?

**Comment by inumanag** [comment]
Hi @gusaaaaa,

I can think of simple version that runs `sleep(1)` in a loop and runs the callback.
The callback can be defined as:

```
from time import sleep
@extern
def one_second(callback: Function[[int], int]):
   while True:
      i = callback(42)
      if i == 0: break  # or your condition
      sleep(1)
```

Bear in mind that Codon has GC and is not a real-time platform. As long as you are not making an real-time component, this should be fine.
