### ISSUE TITLE
`os.environ.setdefault` does not work

### ISSUE THREAD

**Issue by Real-Gecko** [exaloop/codon#583]
Creating test file
```python
# test.py
import os

os.environ.setdefault("lala", "tralala")
```

Running with `codon`
```sh
$ codon run test.py
test.py:3:1-41: error: 'EnvMap' object has no attribute 'setdefault'
$ codon build -release -exe test.py
test.py:3:1-41: error: 'EnvMap' object has no attribute 'setdefault'
```

**Comment by avitkauskas** [comment]
Codon has very limited native `os` module implementation yet.
I sent a PR to implement this particular functionality.

Meanwhile, you can use python module:
```python
from python import os

os.environ.setdefault("lala", "tralala")
```

**Comment by inumanag** [comment]
Hi @Real-Gecko ,

Yes, @avitkauskas  is right---our `os.environ` implementation is pretty bare-bones at the moment. I'd also second using `from python` import for now.

**Comment by inumanag** [comment]
Merging into #608 .
