### ISSUE TITLE
Multiple unwanted Threads

### ISSUE THREAD

**Issue by sinainnet** [exaloop/codon#584]
Hi, I have created the following program:
```
while True: 
      continue 
```

I have compiled it with the following command:
```
codon build --release -o test test.codon
````

But, when I am running it, it creates a lot of unwanted threads!

![image](https://github.com/user-attachments/assets/cc74177c-3c44-4367-9b39-982c3ff75770)

I do not want those threads! What should I do?

**Comment by arshajii** [comment]
Can you try setting the environment variable `OMP_NUM_THREADS` to `1` (i.e. `export OMP_NUM_THREADS=1`)?

**Comment by sinainnet** [comment]
It is the same!

**Comment by sinainnet** [comment]
I have installed the codon by this:

```
codon build --release -o test test.codon

```

**Comment by sinainnet** [comment]
Yes, that is working. Perfect. So, my question is what would be the performance impact if I set the number of GC threads to 1?

**Comment by inumanag** [comment]
Hi @sinainnet 

I'd expect some performance penalties there, but hard to say in general as it depends on your use-case. GC threads are quite lightweight and you can typically ignore their presence.
