### ISSUE TITLE
Allow CODON_PYTHON to point to executable rather than library

### ISSUE THREAD

**Issue by orent** [exaloop/codon#591]
If dlopen(CODON_PYTHON) fails and the dlerror() string contains 'executable' it means it is pointing to an executable rather than a library.

So run this executable it with arguments '-m', 'sysconfig', search the output for a line containing LDLIBRARY, take the value after the '=' and use that instead.

**Comment by inumanag** [comment]
Hi @orent 

Do you mind clarifying this? Not all Python executables ship with a dynamic library, hence that would not be the best solution at the moment. I do agree that there should be a better way of handling this, though...

**Comment by orent** [comment]
All python.org releases on windows, linux and mac do. Other than obscure embedded versions of python, I don't recall encountering python without a dynamic library for over a decade an a half.

You can find an even more complete method for finding the library here:

https://github.com/JuliaPy/PyCall.jl/blob/master/deps/find_libpython.py
