### ISSUE TITLE
Pip install codon does not work.

### ISSUE THREAD

**Issue by huolanmiao** [exaloop/codon#593]
Collecting codon
  Using cached codon-0.0.1.tar.gz (21 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      running egg_info
      creating C:\Users\li862\AppData\Local\Temp\pip-pip-egg-info-z7yf8sw3\codon.egg-info
      writing C:\Users\li862\AppData\Local\Temp\pip-pip-egg-info-z7yf8sw3\codon.egg-info\PKG-INFO
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\li862\AppData\Local\Temp\pip-install-b_5xmt0s\codon_d6ad1ba69d94479fb0fc93d735ecc47e\setup.py", line 18, in <module>
          setup(
        File "D:\anaconda\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by huolanmiao** [comment]
Collecting codon
  Using cached codon-0.0.1.tar.gz (21 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by fnhirwa** [comment]
This pypi package is not for the `codon` compiler. There is no pypyi package for this project to install codon you need to run
```shell
/bin/bash -c "$(curl -fsSL https://exaloop.io/install.sh)"
```
And it is only supported for Linux (x86_64) and macOS (x86_64 and arm64).

**Comment by inumanag** [comment]
`pip install codon-jit` only installs Codon's Python integration. You might need to do `pip install setuptools` prior to that.
