### ISSUE TITLE
Why Does the Instance in Codon Script Never Get Terminated After Deletion?

### ISSUE THREAD

**Issue by gyuro** [exaloop/codon#597]
I've written a Codon script that includes a class and a function to be exported:

```python
class Foo:
    def __init__(self):
        print('ctor')
        
    def __del__(self):
        print('dtor')

@export
def func():
    foo = Foo()
    ## before
    del foo
    ## after
```

I noticed something strange: the instance created never gets properly terminated. It shows only `ctor`. After printing the `__raw__` and `__ptr__` values both before and after calling `del foo`, I found that while the `__raw__` value changes slightly:

```
foo.__raw__(): 0x7f6d1f342a80 -> 0x7f6d1f342a40
```

The `__ptr__` value remains the same:

```
__ptr__(foo): 0x7f6c59c94a10 (still unchanged)
```

Could you help me understand and resolve this issue?

**Comment by inumanag** [comment]
`del` just marks the object for deletion; the exact time of deletion completely depends on GC. Sometimes it is immediate, sometimes it only happens upon the program termination. `__del__` will only get executed when GC collects the object.

**Comment by gyuro** [comment]
@inumanag, is there a way to force the GC to collect an object from codon or c++ side?

**Comment by inumanag** [comment]
I think not; @arshajii can provide a more concrete answer.
