### ISSUE TITLE
Yet another file extension?

### ISSUE THREAD

**Issue by AndreiMoraru123** [exaloop/codon#602]
Hi folks, I haven't yet tried codon, but I love the idea.

What throws me off, from the perspective of a user, is this:

```gitattributes
*.codon linguist-language=Python
```

I see that codon is not a new-new language. It advertises itself as a Python compiler, so it makes sense to benefit from Python tooling as well (LSP, linter, formatter, and all that)

A lot of these tools pick up on the file name extension. For instance, that's how LSP clients work in neovim:

![image](https://github.com/user-attachments/assets/e5db35d4-78da-4a89-a127-cd5ae620eef1)

Yes, there are ways to work around that, like registering the file extension:

```lua
vim.filetype.add({
    extension = {
        codon = "python",
    },
})
```

That's the happy case for a customizable editor, and even here it's one extra thing you have to do.

For vscode I can "cheat" by initially creating a file named `.py` and then renaming it `.codon`.  That seems to also allow tools like Pylance, Ruff, and user shortcuts defined from .py files to work. Still, one extra step you have to take is the happy case for a customizable editor.

An IDE like PyCharm, otoh, might have it the worst. I haven't used it in a minute, but IIRC, it does not allow users to create their own extensions for Python files. You could of course create it from the CLI or from outside the editor, but I assume you would get zero tooling for that. 

I understand that codon has a syntax that indeed does not exist in Python, like the [pipelines](https://docs.exaloop.io/codon/advanced/pipelines), so in time, it might be more sensible for codon to have its own LSP, linters, and even syntax highlighting since the AST will be different, as it outgrows python.

But for now, the repo description is still:

"A high-performance, zero-overhead, extensible Python compiler using LLVM"

and not:

"A high-performance, zero-overhead, extensible programming language using LLVM"

Cython never really picked up in part also because of the subpar tooling while trying to be a different programming language.
Codon luckily has none of that syntax malarkey, but it has all the benefits of having a 99% Python affinity, so it doesn't have to fight the whole uphill battle of a new PL.

**Comment by arshajii** [comment]
Thanks for the thoughtful post, @AndreiMoraru123! Yes in general it's totally fine to use `.py` and general Python tools/editors; we also support/use `.codon` internally for cases that utilize Codon-specific features or libraries. But our goal is to integrate as much as possible with the existing Python ecosystem, so I think we're in agreement there!
