### ISSUE TITLE
Persistent Memory Leak in C++ Loop When Repeatedly Loading and Unloading Shared Library

### ISSUE THREAD

**Issue by gyuro** [exaloop/codon#603]
In Codon, the code is compiled into `foo.so`:

```python
@export
def foo() -> None:
    pass
```

In C++, the main loop is structured as follows:

```cpp
for (;;) {
    // before
    void *handle = dlopen("foo.so", RTLD_LAZY);

    auto foo_func = reinterpret_cast<void (*)()>(dlsym(handle, "foo"));
    foo_func();

    dlclose(handle);
    // after
}
```

The problem appears when this loop runs repeatedly—virtual memory usage steadily increases, indicating a significant memory leak between the "before" and "after" points.

Is this a known issue?

**Comment by inumanag** [comment]
Seems related to #452.

**Comment by gyuro** [comment]
@inumanag, I also found that the approach suggested by @arshajii in [this GitHub comment](https://github.com/exaloop/codon/issues/452#issuecomment-1695838282) works well. However, my situation is a bit different, as my program needs to reload dynamically on demand, so it has to support reloading during runtime.

I found a workaround that allows it to work consistently without errors. When `dlopen` is called with the `RTLD_NODELETE` option, it seems to function correctly, with no memory leaks observed. I've paused my investigation into the Codon engine code for now, but could you please confirm if this solution is technically sound?

**Comment by inumanag** [comment]
Thank you for the solution, @gyuro---I was not aware of `RTLD_NODELETE`! Based on the docs, it looks OK. We should probably add this to the docs.
