### ISSUE TITLE
cannot import name 'RollingMedian' from 'vec'

### ISSUE THREAD

**Issue by River-Shi** [exaloop/codon#605]
Here is my `extension.codon` file
```
import collections

class RollingMedian:
    n: int 
    data: collections.deque[float]

    def __init__(self, n: int = 10):
        self.n = n
        self.data = collections.deque(maxlen=n)

    def input(self, value: float) -> float:
        self.data.append(value)
        return self.get_median()
        

    def get_median(self) -> float:
        sorted_data = sorted(self.data)
        mid = len(sorted_data) // 2

        if len(sorted_data) % 2 == 0:
            return (sorted_data[mid - 1] + sorted_data[mid]) / 2.0
        else:
            return sorted_data[mid]
```
I run `python3 setup.py build_ext --inplace` and got:
```
Found Codon: /Users/river/.codon
running build_ext
/Users/river/.codon/bin/codon build -release --relocation-model=pic -pyext -o build/lib.macosx-11.0-arm64-cpython-310/vec.cpython-310-darwin.so.o -module vec extension.codon
clang -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/river/miniforge3/lib -L/Users/river/miniforge3/lib -Wl,-rpath,/Users/river/miniforge3/lib -L/Users/river/miniforge3/lib -Wl,-rpath,@loader_path build/lib.macosx-11.0-arm64-cpython-310/vec.cpython-310-darwin.so.o -L/Users/river/.codon/lib/codon -Wl,-rpath,/Users/river/.codon/lib/codon -lcodonrt -o build/lib.macosx-11.0-arm64-cpython-310/vec.cpython-310-darwin.so
ld: warning: duplicate -rpath '/Users/river/miniforge3/lib' ignored
ld: warning: object file (/Users/river/Desktop/pyext/build/lib.macosx-11.0-arm64-cpython-310/vec.cpython-310-darwin.so.o) was built for newer 'macOS' version (14.0) than being linked (11.0)
copying build/lib.macosx-11.0-arm64-cpython-310/vec.cpython-310-darwin.so ->
```
Then I tried to `from vec import RollingMedian`, but got:
```
Traceback (most recent call last):
  File "/Users/river/Desktop/pyext/test.py", line 1, in <module>
    from vec import RollingMedian
ImportError: cannot import name 'RollingMedian' from 'vec' (/Users/river/Desktop/pyext/vec.cpython-310-darwin.so)
```

**Comment by River-Shi** [comment]
> Here is my `extension.codon` file
> 
> ```
> import collections
> 
> class RollingMedian:
>     n: int 
>     data: collections.deque[float]
> 
>     def __init__(self, n: int = 10):
>         self.n = n
>         self.data = collections.deque(maxlen=n)
> 
>     def input(self, value: float) -> float:
>         self.data.append(value)
>         return self.get_median()
>         
> 
>     def get_median(self) -> float:
>         sorted_data = sorted(self.data)
>         mid = len(sorted_data) // 2
> 
>         if len(sorted_data) % 2 == 0:
>             return (sorted_data[mid - 1] + sorted_data[mid]) / 2.0
>         else:
>             return sorted_data[mid]
> ```
> 
> I run `python3 setup.py build_ext --inplace` and got:
> 
> ```
> Found Codon: /Users/river/.codon
> running build_ext
> /Users/river/.codon/bin/codon build -release --relocation-model=pic -pyext -o build/lib.macosx-11.0-arm64-cpython-310/vec.cpython-310-darwin.so.o -module vec extension.codon
> clang -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/river/miniforge3/lib -L/Users/river/miniforge3/lib -Wl,-rpath,/Users/river/miniforge3/lib -L/Users/river/miniforge3/lib -Wl,-rpath,@loader_path build/lib.macosx-11.0-arm64-cpython-310/vec.cpython-310-darwin.so.o -L/Users/river/.codon/lib/codon -Wl,-rpath,/Users/river/.codon/lib/codon -lcodonrt -o build/lib.macosx-11.0-arm64-cpython-310/vec.cpython-310-darwin.so
> ld: warning: duplicate -rpath '/Users/river/miniforge3/lib' ignored
> ld: warning: object file (/Users/river/Desktop/pyext/build/lib.macosx-11.0-arm64-cpython-310/vec.cpython-310-darwin.so.o) was built for newer 'macOS' version (14.0) than being linked (11.0)
> copying build/lib.macosx-11.0-arm64-cpython-310/vec.cpython-310-darwin.so ->
> ```
> 
> Then I tried to `from vec import RollingMedian`, but got:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/river/Desktop/pyext/test.py", line 1, in <module>
>     from vec import RollingMedian
> ImportError: cannot import name 'RollingMedian' from 'vec' (/Users/river/Desktop/pyext/vec.cpython-310-darwin.so)
> ```

Here is my code [repo](https://github.com/River-Shi/pyext)

**Comment by inumanag** [comment]
You need to add `@dataclass(python=True)` to all classes that are to be used from Python (e.g., for `RollingMedian`) for this to work.

**Comment by inumanag** [comment]
`deque` does not yet have Python bindings implemented. Adding this to out TODO list. In the meantime, you can use `List`.

**Comment by River-Shi** [comment]
> `deque` does not yet have Python bindings implemented. Adding this to out TODO list. In the meantime, you can use `List`.

Thanks, may I ask when will it be supported?

**Comment by inumanag** [comment]
Hopefully in the next couple of releases, but no exact ETA at the moment.
