### ISSUE TITLE
[Bug] what():  argument not found

### ISSUE THREAD

**Issue by zhouzaida** [exaloop/codon#81]
Hi, thanks for your awesome work. I followed the example in https://docs.exaloop.io/codon/#codon-at-a-glance and got an error.

```
$ codon run -release fib.py
terminate called after throwing an instance of 'fmt::v9::format_error'
  what():  argument not found
[1]    971 abort      codon run -release fib.py
```

**Comment by arshajii** [comment]
I think this is actually due to https://github.com/exaloop/codon/issues/75 (Codon throwing an exception on non-existent file) -- can you check if `fib.py` exists in the current directory?

**Comment by zhouzaida** [comment]
Thanks for your reply. I checked and it did not exist.
