### ISSUE TITLE
[help] GPU error

### ISSUE THREAD

**Issue by tiendung** [exaloop/codon#89]
I built codon from source with gpu support and try to run a simple gpu code but got following error. How should i fix it? thanks.

```
$ ./build/codon run gpu.py
CUDA error at /home/t/repos/codon/codon/runtime/gpu.cpp:42: a PTX JIT compilation failed
Aborted
```

gpu.py code:
```py
import gpu

@gpu.kernel
def hello(a, b, c):
    i = gpu.thread.x
    c[i] = a[i] + b[i]

a = [i for i in range(16)]
b = [2*i for i in range(16)]
c = [0 for _ in range(16)]

hello(a, b, c, grid=1, block=16)
```

It can generate .ptx file, the content is at https://gist.github.com/tiendung/c0d97a89cf3d07332e4c41aae3abd72e

**Comment by arshajii** [comment]
Hi @tiendung -- Can you try running with `-release` (`./build/codon run -release gpu.py`)?

**Comment by tiendung** [comment]
> Hi @tiendung -- Can you try running with `-release` (`./build/codon run -release gpu.py`)?

It works! Thank you.
