### ISSUE TITLE
Significantly slow when calling some functions like `random.seed()`

### ISSUE THREAD

**Issue by 1MLightyears** [exaloop/codon#93]
Hi I'm trying to see if `codon` production is faster than directly run codes with `CPython` intepreter.
And happened to find it wrong in some cases.

It seems that when calling some std functions, `codon`'s performance is worse than `CPython` but I don't know what was wrong.
I'll put my codes and benchmark bash script below, hope someone would like to give it a look or run it on their own to see if that only happens on me.

**Comment by 1MLightyears** [comment]
OS: Ubuntu 20.04.5 LTS (Windows Subsystem for Linux, wsl1)
Python: Python 3.8.10 (default, Nov 14 2022, 12:59:47)
codon: 0.15.1

`test.py`:
```python3
from random import seed, random
from datetime import datetime
from math import sqrt

seed(datetime.now().microsecond)
r=0
total = 4000000
hit = 0
for i in range(total):
    r=random()
    if sqrt(r) > 0.99:
        hit+=1
print(f"finish, total={total}, rate={hit/total*100:2.4}%")
```
benchmark script output for `test.py`:
```bash
>>> python3 test.py
finish, total=4000000, rate=1.981%

real    0m0.620s
user    0m0.469s
sys     0m0.063s

>>> codon test.py (build+run)
finish, total=4000000, rate= 2%

real    0m0.709s
user    0m0.563s
sys     0m0.016s
=====
```
looks good here, but the problems appeared later:

`test_seed.py` (with calling `random.seed()`):
```python3
from random import seed, random
from datetime import datetime
from math import sqrt,floor

seed(datetime.now().microsecond)
r=0
total = 4000000
hit = 0
for i in range(total):
    r=random()
    if sqrt(r) > 0.99:
        seed(i)
        hit+=1
print(f"finish, total={total}, rate={hit/total*100:2.4}%")
```
benchmark script output on  `test_seed.py`:
```bash
>>> python3 test_seed.py
finish, total=4000000, rate=1.997%

real    0m0.941s
user    0m0.875s
sys     0m0.063s

>>> codon test_seed.py (build+run)
finish, total=4000000, rate=1.997%

real    0m2.459s
user    0m2.438s
sys     0m0.016s
=====
```
The time spent on user mode is sharply high compared with running directly by `CPython`. The only difference is we called approx. 80000 times of `random.seed()`.

`test_seed_more.py`:
```python3
from random import seed, random
from datetime import datetime
from math import sqrt,floor

seed(datetime.now().microsecond)
r=0
total = 4000000
hit = 0
for i in range(total):
    r=random()
    if sqrt(r) > 0.9:
        seed(i)
        hit+=1
print(f"finish, total={total}, rate={hit/total*100:2.4}%")
```
Increase to approx 800000 calls of `random.seed()`, the result shows that it really is the key to the problem:
benchmark script output on  `test_seed_more.py`:
```bash
>>> python3 test_seed_more.py
finish, total=4000000, rate=19.01%

real    0m4.843s
user    0m4.813s
sys     0m0.031s

>>> codon test_seed_more.py (build+run)
finish, total=4000000, rate=19.01%

real    0m19.626s
user    0m19.547s
sys     0m0.016s
=====
```
Other std functions like `datetime.datetime.now()` does not make any difference:
`test_datetime.py`
```python3
from random import seed, random
from datetime import datetime
from math import sqrt,floor

seed(datetime.now().microsecond)
r=0
total = 4000000
hit = 0
s = 0
for i in range(total):
    r=random()
    if sqrt(r) > 0.99:
        s += datetime.now().microsecond
        hit+=1
print(f"finish, total={total}, rate={hit/total*100:2.4}%")
```
benchmark script output on  `test_datetime.py`:
```bash
>>> python3 test_datetime.py
finish, total=4000000, rate=1.983%

real    0m0.642s
user    0m0.609s
sys     0m0.031s

>>> codon test_datetime.py (build+run)
finish, total=4000000, rate=2.011%

real    0m0.648s
user    0m0.563s
sys     0m0.078s
=====
```
Let me say again that I haven't look into this case so I currently have no idea what lies behind.
I'll also place my `benchmark.sh` here.

```bash
#! /bin/bash
# this should be your codon path
# I ran the benchmark under codon-deploy/bin and all my test python scripts are there too
CODON="./codon" 

PATTERN="test.*?\.py"
echo -e "===benchmark on python v. codon==="
echo -e "python version:"
python3 -V

echo -e "\ncodon version:"
$CODON --version

echo -e "\n======\n"

for FILE in `ls` 
do
    if [[ $FILE =~ $PATTERN ]]
    then
        echo -e "\n>>> python3 $FILE"
        time (python3 $FILE)
        echo -e "\n>>> codon $FILE (build+run)"
        $CODON build -o $FILE.elf $FILE
        time (./$FILE.elf)
        rm ./$FILE.elf
        echo -e "=====\n"
    fi
done
```
Thanks and btw do we need time benchmarks for users? I've seen quite a lot test cases in the `test/`, then if `codon` is really more effecient maybe offering and acing some timing benchmarks are more persuasive.

**Comment by arshajii** [comment]
Hi @1MLightyears -- it doesn't look like you're enabling optimizations. Can you try adding the `-release` flag, as in `$CODON build -release -o $FILE.elf $FILE`?

**Comment by 1MLightyears** [comment]
Thank you for your reply! After adding the `-release` switch the time spent reduced quite a lot. Now the performances between `codon` and `CPython` are alike.
I know in actual occasions initiallizing random number generator for some thousands of times is very rare, I just bump into it.
This issue could be marked as solved. If I'm glad to provide some timing benchmarks, would PR be accepted?
