### ISSUE TITLE
libpython path/name issue (with solution)

### ISSUE THREAD

**Issue by uselibrary** [exaloop/codon#97]
The codon uses `libpython.so` as the default python library. However, there is a path/name issue among Linux distributions. For example, Debian (11) uses specific name libpython3.9.so rather than libpython.so. Currently, I set up a soft-link for this issue:
```
ln -s /usr/lib/x86_64-linux-gnu/libpython3.9.so /usr/lib/x86_64-linux-gnu/libpython.so
```

**Comment by arshajii** [comment]
You can also set the environment variable `CODON_PYTHON` to point to the correct shared library ([docs](https://docs.exaloop.io/codon/interoperability/python)):

```bash
export CODON_PYTHON=/usr/lib/x86_64-linux-gnu/libpython3.9.so
```
